- Capfile
- dotenv.sample
Also expands the dotenv.sample for upcoming db work.
> Fixes issue with Capfile

- HARVESTING_ALMA_DATA.md
HARVESTING_ALMA_DATA.md: copies the instructions from [our wiki](https://wiki.emory.edu/display/BDL/Using+SolrMarc+to+harvest+data+from+Alma+into+Solr+Index) to this Markdown file.
> Creates Alma harvesting instructions README.me (#77).

- lib/tasks/solrmarc/README.md
Adds documentation for mapping as we have it now.
> Documentation for mapping

- HARVESTING_ALMA_DATA.md
HARVESTING_ALMA_DATA.md: amends markdown file to reflect the optional `oai_set_name` variable.
> Updates HARVESTING_ALMA_DATA.md with new variable option (#89).

- lib/tasks/sample_scheduler.rake
Corrects variable name typo when calling `deleted_records`
> Corrects variable name for deleted_records

- app/controllers/catalog_controller.rb
- db/schema.rb
- lib/tasks/solrmarc/index.properties
- solr/conf/schema.xml
- spec/system/targeted_field_search_spec.rb
- lib/tasks/solrmarc/index.properties: maps the newly created fields needed for this configuration.
- solr/conf/schema.xml: creates additional title fields to perform the search.
> Configures MARC Fields for Title Search

- app/controllers/catalog_controller.rb
- lib/tasks/solrmarc/index.properties
- solr/conf/schema.xml
- spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb (added keyword field per https://docs.google.com/spreadsheets/d/1jSqgNd6HnVJdJMrrShAofkmK8uGgHGdlKODmZOL5NfY/edit#gid=1979033236 speardsheet)
- spec/system/targeted_field_search_spec.rb (tested the new keyword fields)
> Refines Keyword Basic Search

- app/controllers/catalog_controller.rb
- lib/marc_indexer.rb
- spec/controllers/catalog_controller_spec.rb
- spec/models/marc_indexing_spec.rb
- spec/support/solr_documents/item.rb
- spec/system/targeted_field_search_spec.rb
This PR tries to get our mappings as close as possible to the working metadata worksheet model. We are also making an attempt to map content types correctly this time.
> Adds initial work for mapping format and new fields

- app/controllers/catalog_controller.rb
- lib/marc_indexer.rb
- lib/tasks/solrmarc/index.properties
- solr/README.md
- spec/system/targeted_field_search_spec.rb
All: changes field definitions to address errors in ingestion.
> Bug: Corrects additional fields causing errors during ingest.

- config/deploy.rb
This PR will fix deploy issues with blacklight test
> Set passenger to restart with touch

- app/controllers/catalog_controller.rb
- lib/marc_indexer.rb
- spec/controllers/catalog_controller_spec.rb
- spec/support/solr_documents/item.rb
- spec/system/view_search_results_spec.rb
Search results page:
Expanded view:
> Adds new genre facet field as per requirements

- app/controllers/catalog_controller.rb
- lib/marc_indexer.rb
- spec/controllers/catalog_controller_spec.rb
- spec/support/solr_documents/item.rb
All: updates the genre field name to remove `facet`.
> Removes `facet` from genre field name.

- app/controllers/catalog_controller.rb
- lib/marc_indexer.rb
- spec/controllers/catalog_controller_spec.rb
- spec/support/solr_documents/item.rb
Search results page:
Expanded view:
> Adds new author facet field as per requirements

- .rubocop.yml
- spec/models/property_bag_spec.rb
spec/models/property_bag_spec.rb: runs tests on the model's functionality.
> Tests that the PropertyBag methods function correctly (#257).

- README.md
Updates verbiage to advise of possible MySQL steps.
> Updates verbiage in README to include MySQL information (#244).

- app/controllers/catalog_controller.rb
app/controllers/catalog_controller.rb: allows up to 25 options for both Library and Resource Type.
> Updates the number of facet options listed for Library and Resource Type (#275).

- .gitignore
- README.md
- jmeter/blacklight_catalog.jmx
- .gitignore: ignores jmeter logs so that we don't bring irrelevant data to production.
- README.md: adds instructions to run jmeter test suite.
- jmeter/blacklight_catalog.jmx: inserts dynamically created test suite configuration.
> Creates JMeter Test Suite (#253).

- app/controllers/omniauth_callbacks_controller.rb
- app/controllers/omniauth_controller.rb
- app/controllers/omniauth_callbacks_controller.rb: added back a customized cookie.
- app/controllers/omniauth_controller.rb: creates a cookie for the origin page, unless that origin page is the sign_in page.
> Further reworks redirects after login (#318).

- app/controllers/catalog_controller.rb
- app/views/catalog/_metadata_block.html.erb
- lib/traject/extract_subject_display.rb
- spec/models/marc_indexing_spec.rb
- spec/presenters/subjects_genre_presenter_spec.rb
- spec/support/solr_documents/item.rb
- spec/system/view_show_page_spec.rb
* We are modifying how subject display field gets saved by adding separators in between certain values.
> Modifies subject display field

- app/controllers/catalog_controller.rb
- app/controllers/catalog_controller.rb: adds additional long fields to truncate
> adds additional field for truncation

- app/controllers/catalog_controller.rb
- config/metadata/main_metadata.yml
- spec/system/view_show_page_spec.rb
- app/controllers/catalog_controller.rb: edit label
- config/metadata/main_metadata.yml: edit label
- spec/system/view_show_page_spec.rb: fixes test
> removes information for alignment

- config/database.yml
- config/deploy.rb
- config/deploy/prod.rb
- config/deploy/test.rb
* now includes db creation & migrate hooks
* now sets region to us-east-1
> Update capistrano scripts to point to new environments

- package.json
Adds dependencies I saw in deployment worries.
> Attempts to address deployment issues.

- lib/tasks/incremental_update.rake
provide rake task for automated solr indexing.
> add incremental solr reindex rake task

- app/controllers/catalog_controller.rb
- solr/README.md
- spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb:  updates to the latest version of the field 
- solr/README.md: updates to the latest version of the field
- spec/system/targeted_field_search_spec.rb: updates to the latest version of the field
Note: author_addl_tesim field doesn't exist any longer, it was updated to author_addl_display_tesim last month
> fixes advanced search for additional authors 700 marc field

- app/models/concerns/blacklight/solr/document/marc_export.rb
app/models/concerns/blacklight/solr/document/marc_export.rb: tests for the presence of a value in datafield tagged "100" to deliver an author name. If that datafield isn't present, we place the title first, then the publication date. Two methods are made to strip punctuation away from strings, which are utilized where needed. Finally, the enclosing parentheses are deleted from doi strings.
> Revises the formatting of the APA citation (#499).

- app/models/concerns/blacklight/solr/document/marc_export.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb: revises MLA title, volume, edition
> revises MLA title, edition, volumes

- app/controllers/catalog_controller.rb
- spec/system/sort_results_spec.rb
- app/controllers/catalog_controller.rb: adds title sorting in asc and desc order
- spec/system/sort_results_spec.rb: tests for A-Z and Z-A sorting
> refines title sorting

- app/assets/stylesheets/blacklight_catalog/_navbar.scss
- app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss
- app/assets/stylesheets/blacklight_catalog/_variables.scss
Refines top navbar rule alignment, Pagination blocks with larger bottom margins
> Refines top navbar rule alignment, Pagination blocks bottom margins

- README.md
- dotenv.sample
It seems like some of the Alma .env stuff is duplicative? Not sure if that means the code needs some refactoring or the dotenv.sample does.
> Update based on new developer setup from scratch

- app/controllers/catalog_controller.rb
- spec/system/sort_results_spec.rb
> Titleizes relevance label in Sort Options (#551).

- app/views/catalog/_facet_group.html.erb
Fixes a missing responsive breakpoint and styles the Facets menu bar on smaller screens
> Adds a larger breakpoint for facets menu navigation (#575)

- .rubocop.yml
- Gemfile
- Gemfile.lock
- README.md
- config/initializers/simple_form.rb
- config/initializers/simple_form_bootstrap.rb
- config/locales/simple_form.en.yml
- lib/templates/erb/scaffold/_form.html.erb
- Fix view issue - could not authenticate in dev environment using 
database authentication because login page was broken because 
simple_form was not installed
> Allow for dev login

- app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss
- app/assets/stylesheets/blacklight_catalog/_variables.scss
- app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss: alters the styling of the sort widgets.
- app/assets/stylesheets/blacklight_catalog/_variables.scss: adds in a variable for the padding of the pagination line.
> Changes the breakpoints for pagination/page sort (#576).

- app/models/concerns/blacklight/solr/document/marc_export.rb
> adds period at the end of MLA citation

- app/models/concerns/blacklight/solr/document/marc_export.rb
Screenshots are attached to the ticket: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/642
> adds capitalization based on MLA and APA standards

- Gemfile
- Gemfile.lock
- app/views/catalog/_show_request_options.html.erb
Remove helper - whole button opens dropdown, which is slightly different but perhaps better functionality.
> Try removing helper to fix bullet issue on production-like environments

- .circleci/config.yml
- .rubocop.yml
- app/controllers/sessions/social_login.rb
- app/helpers/users_helper.rb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/static/contact.html.erb
- config/routes.rb
- spec/helpers/users_helper_spec.rb
- spec/routing/user_login_route_spec.rb
- spec/system/user_login_spec.rb
* We are adding a new login page that gives options to users how they want to login to the application. On production we will see shib and affiliate login options. While in development we will only see database auth option.
Production:
Development:
> Adds ability to choose how a user wants to login

- app/assets/stylesheets/blacklight_catalog/_buttons.scss
- app/assets/stylesheets/blacklight_catalog/_navbar.scss
- app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss
This pull request addresses the following punch list items:
- Increases padding/margins between prev/next, start-over/back-to-search elements on Single Item View
- Back-to-search button radius
- Vertical alignment of bookmark count number
> Style refinements from punch list

- app/assets/stylesheets/blacklight_catalog/_search_form.scss
- app/views/catalog/_show_request_options.html.erb
This style refinements are for the requesting options.
- Button alignment is centered and flush right (#694)
- Dropdown menus is flush right. (#694)
> Request options style refinements for requesting. (#694)

- app/assets/stylesheets/blacklight_catalog/_more_less.scss
- app/assets/stylesheets/blacklight_catalog/_print.scss
- app/views/catalog/_metadata_block_collapsible.html.erb
Cleaned up styles link for "Show More Titles/Author Information".
- Include +/– in text block
- Style in uppercase to distinguish it from other links
> Cleaner Show More Title/Author links (#694)

- app/models/concerns/statusable.rb
- app/views/catalog/_show_request_options.html.erb
- spec/models/solr_document_spec.rb
- spec/system/view_show_page_spec.rb
> Show the holding level description for periodicals

- app/assets/stylesheets/blacklight_catalog/_notifications.scss
Changes opacity and font-weights to match Emory Libraries Pattern Library
> Updated bootstrap alerts to match Pattern Library (#694)

- app/assets/stylesheets/blacklight_catalog/_facets.scss
- app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss
- app/assets/stylesheets/blacklight_catalog/_variables.scss
Vertical Alignment of Facet title, prev&next and sorting & per-page
> Vertical alignment of search results top navigation. (#694)

- app/controllers/catalog_controller.rb
- app/helpers/tools_sidebar_helper.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb
- spec/controllers/catalog_controller_spec.rb
- spec/models/marc_indexing_spec.rb
Very minimal RIS implementation
```
TY - GEN
AU - 
TI - John F. Kennedy
PB - [W.W. Norton & Company]
CY - nyu
PY - 2016
CN - E841 .J585 2016
ET - First edition.
ER - 
```
> Export ris minimal

- app/assets/stylesheets/blacklight_catalog/_show_page.scss
> Better word wrap style (#694)

- app/assets/stylesheets/blacklight_catalog/_bookmarks.scss
- app/views/bookmarks/_clear_bookmarks_widget.html.erb
- app/views/bookmarks/index.html.erb
Connected to: #569 
From Norm: it needs the cite tool to be functioning but the styles/layout is correct
> Markup and styles for Cite button for display in bookmarks #(694)

- config/schedule.rb
Ref: https://github.com/javan/whenever/issues/665#issuecomment-319259093
> Adds logger for cron and tells whenever where bundler is

- app/controllers/catalog_controller.rb
> Revise the order of the Export to RIS Tool #(799).

- app/views/shared/_footer_list.html.erb
- config/locales/blacklight.en.yml
- app/views/shared/_footer_list.html.erb: changes the text and hrefs' to the new specifications, and localizes all used verbiage. 
- config/locales/blacklight.en.yml: stubs the new localizations used above.
> Updates the footer links' text and hrefs (#803).

- app/assets/stylesheets/blacklight_catalog/_bookmarks.scss
- app/controllers/export_ris_controller.rb
- app/views/bookmarks/_clear_bookmarks_widget.html.erb
- config/locales/blacklight.en.yml
- config/routes.rb
- spec/routing/export_multiple_ris_routes_spec.rb
- spec/system/bookmarks_page_spec.rb
- app/assets/stylesheets/blacklight_catalog/_bookmarks.scss: adds the new button to the citation button styling.
- app/controllers/export_ris_controller.rb: creates a controller to handle the multiple RIS processing.
- app/views/bookmarks/_clear_bookmarks_widget.html.erb: inserts link to the new button action.
- config/locales/blacklight.en.yml: localizes the button's verbiage.
- config/routes.rb: routes the processing to the new controller's action.
- spec/*: tests expectations for this button and it's action.
>  Adds Export RIS to Bookmarks page (#800). 

- app/views/static/contact.html.erb
- config/locales/en.yml
> updates contact form and explore blocks

- app/views/static/about.html.erb
- config/locales/en.yml
- db/schema.rb
> updates text content and explore box on about page

- app/views/static/about.html.erb
- config/locales/en.yml
> edits to about page text per 841

- app/views/advanced/_advanced_search_help.html.erb
> Changes adv search tips verbiage as per requirements

- app/views/layouts/blacklight/base.html.erb
- spec/system/advanced_search_spec.rb
https://user-images.githubusercontent.com/17075287/131571474-a0822dfa-fb34-4f2a-801f-64a28970372d.mov
> Fixes bug where users can reach advanced search page from search results page

- app/assets/stylesheets/blacklight_catalog/_results_list.scss
- app/assets/stylesheets/blacklight_catalog/_variables.scss
- app/services/alma_availability_service.rb
- app/views/catalog/_document_url_fulltext_modal.html.erb
- spec/services/alma_availability_service_spec.rb
- app/assets/stylesheets/blacklight_catalog/_results_list.scss: adjusts certain values, while also throwing other values into variables.
- app/assets/stylesheets/blacklight_catalog/_variables.scss: saves values into variables.
- app/services/alma_availability_service.rb: reworks logic into two new methods that check arrays.
- app/views/catalog/_document_url_fulltext_modal.html.erb: breaks line so that links are separated.
- spec/services/alma_availability_service_spec.rb: updates tests for correct expectations.
> Corrects availability badges styling and logic (#864). 

- .rubocop.yml
- app/views/catalog/_show_request_options.html.erb
- config/initializers/catalog_index_override.rb
- config/initializers/catalog_show_override.rb
- spec/spec_helper.rb
- spec/system/view_show_page_spec.rb
> adds availability badges to show pages

- app/views/devise/shared/_links.html.erb
- spec/system/user_login_spec.rb
#932 
changed wording on test login screen; changed rspec test to reflect new wording.
> Login wording 932

- app/assets/javascripts/alternate_catalog.js
- app/helpers/alternate_catalog_helper.rb
- app/views/catalog/_alternate_catalog.html.erb
- app/views/catalog/_search_results.html.erb
- spec/helpers/alternate_catalog_helper.rb
- spec/system/view_search_results_spec.rb
> implements frontend for articles+ bentobox

- app/controllers/omniauth_controller.rb
- app/controllers/sessions_controller.rb
- app/views/devise/shared/_links.html.erb
- spec/controllers/omniauth_controller_spec.rb
- spec/controllers/sessions_controller_spec.rb
Ticket: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/emory-libraries/blacklight-catalog/940
> 940 - Redirect user to requested page after sign in

- app/assets/stylesheets/blacklight_catalog/_facets.scss
- app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss
small changes to _facets.scss to bring the search results and facets sidebar headings back into alignment.
> Css punchlist 11 search results vertical alignment

- app/assets/stylesheets/blacklight_catalog/_facets.scss
- app/assets/stylesheets/blacklight_catalog/_search_form.scss
- expanded the margin-top of the facets-heading in _facets.scss 
- adjusted the margins of the header-search and gave it a line-height in _search_form.scss
- did some refactoring to variables in _facets.scss
> aligning facet and search headers on home page

- app/views/catalog/_facet_group.html.erb
- app/views/catalog/_show.html.erb
app/views/catalog/_facet_group.html.erb and app/views/catalog/_show.html.erb: updates the labels, actions, and categories to Emily's preference.
No screenshot necessary.
> Corrects gtag categories

- .rubocop.yml
- app/assets/javascripts/catalog.js
- app/views/bookmarks/index.html.erb
- app/views/catalog/_search_results.html.erb
- config/initializers/bookmarks_index_override.rb
> Fix availability indictors on bookmarks page

- app/views/advanced/index.html.erb
- spec/system/bookmarks_page_spec.rb
> Updates the page title for Advanced (#1105).

- app/controllers/availability_indicators_controller.rb
- app/views/catalog/availability/_badges.html.erb
> Add contact us availability indicator

- app/views/shared/_beta_banner.html.erb
> Updates banner text for production release (#1124).

- app/assets/stylesheets/blacklight_catalog/_buttons.scss
- app/assets/stylesheets/blacklight_catalog/_print.scss
- app/assets/stylesheets/blacklight_catalog/_results_list.scss
- app/views/catalog/_index.html.erb
- app/views/catalog/availability/_table.html.erb
- app/assets/*: styles the elements needed to be resized or hidden.
- app/views/*: adds in classes and logic that hide or help select elements for styling.
https://user-images.githubusercontent.com/18330149/145590544-fa509336-7366-4c0d-938f-5fe5066fc384.mov
> Resizes or hides requested elements (#1096).

- config/locales/en.yml
> Update help page

- .rubocop.yml
- app/views/catalog/_home_text.html.erb
- app/views/layouts/blacklight/base.html.erb
- config/initializers/catalog_index_override.rb
- spec/system/ejournals_spec.rb
Reverts emory-libraries/blacklight-catalog#1155
> Revert "Redirects to a blank search results page with overlay when search returns nothing (#1146)."

- app/views/catalog/_zero_results.html.erb
> Changes the text when no results found (#1146).

- dotenv.sample
- lib/tasks/incremental_update.rake
> Add honeybadger check in for incremental update task

- lib/tasks/incremental_update.rake
> Fix Honeybadger check in for Blacklight reindex task

- app/assets/stylesheets/blacklight_catalog/_results_list.scss
> Refine availability table css mobile

- app/services/alma_availability_service.rb
> Bug: removes availability xml namespaces to process all records (#1196).

- app/controllers/catalog_controller.rb
- config/metadata/main_metadata.yml
- spec/system/view_search_results_spec.rb
- spec/system/view_show_page_spec.rb
> Updates the Resource Type label globally (#1200).

- app/views/shared/_beta_banner.html.erb
> Updates the banner's text (#1193).

- app/assets/stylesheets/blacklight_catalog/_print.scss
Fixes #1216:
Bookmarks Example:
https://app.zenhub.com/files/295449627/7d69ab2c-0e76-4f0c-b15c-fe0631e80da7/download
Search Results Example:
https://app.zenhub.com/files/295449627/4423d844-8f08-4e20-a927-8c7dd7e76154/download
> Update CSS for bookmarks and search results print

- app/views/catalog/_zero_results.html.erb
> Add reference to ILL when no results are found

- app/views/catalog/_home_text.html.erb
- app/views/shared/_header_navbar.html.erb
> Update homepage and remove beta banner

- app/controllers/catalog_controller.rb
- solr/conf/schema.xml
> Add custom field types `isbn_t`, `issn_t`, and `lc_callnum`

- solr/conf/schema.xml
- spec/system/advanced_search_spec.rb
- solr/conf/schema.xml: adds X into patterns as an acceptable character.
- spec/system/advanced_search_spec.rb: adds tests to check that the above pattern is working and refactors file to DRY it up.
> Adds X as an acceptable character in ISSN/ISBN (#1260).

- app/views/shared/_beta_banner.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_beta_banner.html.erb: updates text to desired verbiage.
- app/views/shared/_header_navbar.html.erb: activates banner partial.
> Adds banner announcing Illiad downtime.

- app/views/static/contact/_assistance.html.erb
- spec/system/view_help_page.rb
- app/views/static/contact/_assistance.html.erb: changes to desired LibWizard form.
- spec/system/view_help_page.rb: authors test to check proper link.
> ServiceNow: update Ask eJournal destination (#1283).

- lib/marc_indexer.rb
- lib/traject/extract_genre.rb
- lib/traject/extract_subject.rb
- lib/traject/extract_subject_display.rb
- lib/traject/extract_subject_era.rb
- lib/traject/extract_subject_geo.rb
- lib/traject/extraction_tools.rb
- spec/fixtures/alma_marc_resource.xml
- spec/models/marc_indexing_spec.rb
> Revise subject field mappings

- Gemfile
- Gemfile.lock
- app/helpers/catalog_helper.rb
- app/presenters/addl_ids_presenter.rb
- app/presenters/addl_titles_presenter.rb
- app/presenters/description_summary_presenter.rb
- app/presenters/field_presenter.rb
- app/presenters/main_metadata_presenter.rb
- app/presenters/related_names_presenter.rb
- app/presenters/subjects_genre_presenter.rb
- app/views/catalog/show_tools/_metadata_block.html.erb
- app/views/catalog/show_tools/_metadata_block_collapsible.html.erb
Feature Branch Ticket: #1325 
Ticket: #1327 
- Upgrade `blacklight` to `7.33`
- Resolve all show page related issues to ensure most features are functional
This is the first of many PRs to upgrade Blacklight to 7.33 in the feature branch `abel-1325-upgrade_blacklight_7_33`. In this PR, I upgrade the gem, and resolve all issues tied to essential functionalities. There are less than 20 rspec failures in this branch, which will be resolved in future PRs. Most changes in this PR are aimed at fixing the show page, which is now fully functional. Refer to the screenshot below:
> Resolve show page issues

- app/helpers/search_results_helper.rb
- app/views/catalog/_title_starts_with_index.html.erb
- app/views/static/ejournals.html.erb
- spec/helpers/search_results_helper_spec.rb
> Refactor ejournals/title starts with views

- PODMAN.md
- podman-compose.yml
Ticket: #1367 
Use Podman to create containers for Solr and MySQL:
- Add podman compose file
- Add setup instructions
> Add Podman setup

- app/assets/stylesheets/blacklight_catalog/_other_resources_accordions.scss
- app/views/catalog/other_resources/_accordion_panel.html.erb
Resolve issues from the Lighthouse report
> Edit accordion panel view

- lib/traject/extract_genre.rb
- lib/traject/extract_subject.rb
Ticket: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/librarysearch-enhance/37
> Add rbmscv to valid sources for subject and genre

- .rubocop.yml
- lib/solr/create_collection_alias.rb
- lib/solr/create_collection_hotspare.rb
- lib/solr/create_solr_core.rb
- lib/solr/delete_solr_collection.rb
- lib/solr/delete_solr_collection_alias.rb
- lib/solr/solr_backup.rb
- lib/solr/solr_restor.rb
- lib/solr/solr_restor_testing.rb
- lib/solr/solr_restore_snapshot.rb
Ticket: [#1381](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/blacklight-catalog/1381)
- Add existing Solr related scripts
- Add new script to create a collection hot spare
> Add Solr scripts

- app/views/static/contact/_assistance.html.erb
- app/views/static/contact/_explore_card.html.erb
- spec/models/marc_indexing_spec.rb
> Fix broken links on help page

- app/assets/javascripts/alternate_catalog.js
> Blacklight 7.33 Upgrade: Fix articles plus view position

- Gemfile
- Gemfile.lock
- app/controllers/catalog_controller.rb
- config/metadata/main_metadata.yml
- spec/system/front_page_spec.rb
- spec/system/view_search_results_spec.rb
- spec/system/view_show_page_spec.rb
[Ticket](https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/librarysearch-enhance/44)
> Adds xray rails gem and changes resource type to format.

- app/components/blacklight/facet_field_component.html.erb
- config/features.rb
Ticket: https://app.zenhub.com/workspaces/blacklight-catalog-5f5f84a8a6d29939a0bc5d78/issues/gh/emory-libraries/librarysearch-enhance/43
> Add experimental feature to open the access facet by default on the homepage

- config/language_filter.yml
added rationale and one more term
> Language additions

- app/services/alma_availability_service.rb
- spec/fixtures/alma_sru_availability/sru_multi_physical_holding_types.xml
- spec/fixtures/alma_sru_availability/sru_multi_physical_holdings.xml
- spec/fixtures/alma_sru_availability/sru_multi_records.xml
- spec/fixtures/alma_sru_availability/sru_online_holding.xml
- spec/fixtures/alma_sru_availability/sru_physical_holding.xml
- spec/services/alma_availability_service_spec.rb
- spec/spec_helper.rb
- spec/system/view_search_results_spec.rb
- spec/system/view_show_page_spec.rb
> Use SRU to query availability
