emory-libraries/blacklight-catalog

config/environments/production.rb
Blacklight uses ES6 syntax, which only works with Uglifier's "harmony" mode.
=> Uses "harmony" mode for Uglifier

.circleci/config.yml, .gitignore, config/database.yml, db/schema.rb
- .circleci/config.yml: resets database configuration to mirror Lux.
- .gitignore: forgets all files that start with `.env`.
- config/database.yml: copies database settings from Lux.
- db/schema.rb: rewrites schema to MySQL specs.
=> Swaps out sqlite for MySQL2 (#43).

db/migrate/20201123172207_remove_email_index_from_users.rb, db/migrate/20201123172331_allow_null_email_in_users.rb, db/schema.rb
- db/migrate/20201123172207_remove_email_index_from_users.rb: removes email index causing error.
- db/migrate/20201123172331_allow_null_email_in_users.rb: allows emails to be null.
- db/schema.rb: updates schema with requested changes.
=> Allow null emails remove index 10

db/migrate/20201124131933_add_trackable_to_devise.rb, db/schema.rb
- db/migrate/20201124131933_add_trackable_to_devise.rb: creates columns needed for Devise's trackable feature.
- db/schema.rb: reflects updated schema with new columns.
=> Adds trackable required columns to users (#10).

app/models/user.rb, app/views/shared/_user_util_links.html.erb, spec/models/user_spec.rb
app/models/user.rb, app/views/shared/_user_util_links.html.erb, and spec/models/user_spec.rb: directly mirroring Lux code, this changes the assignment of a user's attributes and provides error protection, as well as eliminating the need for link `edit_user_registration_path` to be in the header, and updating testing expectations.
=> Corrects edit_user_registration_path error by eliminating that link (#10).

dotenv.sample, lib/tasks/sample_scheduler.rake
- dotenv.sample: sets the default value to `blacklighttest`.
- lib/tasks/sample_scheduler.rake: replaces hard set value with ENV variable.
=> Wires oai_set to an ENV variable so that it can be set in the rake call (#80).

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/support/solr_documents/item.rb, spec/support/solr_helpers.rb, spec/system/view_search_results_spec.rb
- app/controllers/catalog_controller.rb wipes out unnecessary fields and adds the requested ones.
- spec/controllers/catalog_controller_spec.rb: tests for only requested fields to be added to index.
- spec/support/solr_documents/item.rb: creates item for testing.
- spec/support/solr_helpers.rb: provides a method to wipe out Solr container.
- spec/system/view_search_results_spec.rb: checks view expected text and link.
=> Adds search result page metadata (#87).

.rubocop.yml, app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/support/solr_documents/item.rb, spec/system/view_search_results_spec.rb, spec/system/view_show_page_spec.rb
- .rubocop.yml: excludes catalog controller from the Rubocop BlockLength rule.
- app/controllers/catalog_controller.rb: initiates only the requested metadata into the show view.
- spec/controllers/catalog_controller_spec.rb: sets expectations for what show fields are included into the controller.
- spec/support/solr_documents/item.rb: expands the `TEST_ITEM` to include expected fields.
- spec/system/view_search_results_spec.rb: corrects the variable term to reflect what we are testing for.
- spec/system/view_show_page_spec.rb: adds testing for the show page.
=> Initiates preliminary item level metadata display (#102).

.rubocop.yml, app/controllers/catalog_controller.rb, app/views/catalog/_facet_group.html.erb, app/views/catalog/_facet_pagination.html.erb, spec/controllers/catalog_controller_spec.rb, spec/support/solr_documents/item.rb, spec/system/front_page_spec.rb, spec/system/view_search_results_spec.rb
- .rubocop.yml: adds `view_search_results_spec.rb` to BlockLength exclusion.
- app/controllers/catalog_controller.rb: inserts the fields that will be faceted on index pages.
- spec/controllers/catalog_controller_spec.rb: expands the list of expected facet fields.
- spec/support/solr_documents/item.rb: widens the test item fields.
- spec/system/view_search_results_spec.rb: tests for the facets exclusive to the index page.
=> Adds the fields for facets away from the homepage (#84). [MERGE AFTER PR #114 IN MAIN]

app/controllers/catalog_controller.rb, app/views/catalog/_facet_group.html.erb, app/views/catalog/_facet_pagination.html.erb, spec/controllers/catalog_controller_spec.rb, spec/system/front_page_spec.rb
- app/controllers/catalog_controller.rb: removes unnecessary fields, changes options and labels for the needed, and adds a config variable `homepage_facet_fields` that feeds logic in the facets partial.
- app/views/catalog/_facet_group.html.erb: adds a new variable assignment that chooses the homepage restricted list or all of the fields based on which page the user lands.
- app/views/catalog/_facet_pagination.html.erb: corrects a known bug in Blacklight 7.4.1 that displays the `<span>` tags within the facet modal pagination.
- spec/controllers/catalog_controller_spec.rb: checks that the right fields are being assigned in the blacklight configuration and the `homepage_facet_fields` variable.
- spec/system/front_page_spec.rb: tests the homepage for the right facet count and text.
=> Specifies the fields that will be faceted on the homepage (#83).

.rubocop.yml, app/controllers/catalog_controller.rb, lib/tasks/solrmarc/index.properties, solr/conf/schema.xml, spec/controllers/catalog_controller_spec.rb, spec/system/targeted_field_search_spec.rb
- .rubocop.yml: excludes Rspec files that needed more complexity.
- app/controllers/catalog_controller.rb: provides the fields that this search bar option looks in.
- lib/tasks/solrmarc/index.properties: maps the newly created fields needed for this configuration.
- solr/conf/schema.xml: creates the fields that we needed to perform this search.
- spec/controllers/catalog_controller_spec.rb: tests that all of the options in #86 show in the `search_field` configuration.
- spec/system/targeted_field_search_spec.rb: ensures that all of the fields in this configuration do show up in the search results when provided a common search value.
=> Configures the Keyword option's fields it searches in (#95).

app/controllers/catalog_controller.rb, solr/conf/schema.xml, spec/system/targeted_field_search_spec.rb
* We are adding fields that are required to be searched through using the author target.
* Also updating tests to show results.
* Adding a field to solr schema that was previously missing during mapping.
Temp draft PR against the keyword branch, since this PR branch is off of that branch. Will change base with main once the keyword branch is merged and rerun CI.
=> Configures targeted search for Author

app/controllers/catalog_controller.rb, spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb: changes the Subject field to reflect the needed Solr field `subject_t`.
- spec/system/targeted_field_search_spec.rb: includes testing for the switch of focus for the Subject option.
=> Configures the Subject option in the search bar (#94).

.rubocop.yml, app/controllers/application_controller.rb, app/controllers/catalog_controller.rb, app/controllers/static_controller.rb, app/views/static/not_found.html.erb, config/application.rb, config/environments/development.rb, config/environments/test.rb, config/locales/en.yml, config/routes.rb, spec/requests/not_found_requests_spec.rb, spec/routing/not_found_routes_spec.rb
- .rubocop.yml: excludes my test file from this requirement.
- app/controllers/catalog_controller.rb and app/controllers/application_controller.rb: moves this definition to the application controller so that it's available to all controllers.
- app/controllers/static_controller.rb: creates a new controller for static pages.
- app/views/static/not_found.html.erb: institutes our desired code for the 404 page.
- config/application.rb and config/environments/*: configures the application to make it friendly to customized error pages.
- config/locales/en.yml: diverts text to a localization.
- config/routes.rb: stubs a route for the 404 requested action.
- spec/*: tests for intended behavior.
=> Creates a custom 404 page (#143).

app/controllers/catalog_controller.rb, lib/marc_indexer.rb, spec/system/targeted_field_search_spec.rb
Changes all occurrences of `title_abbr_tesi` to `title_abbr_tesim` to correct ingestion error:
2021-02-02T12:37:29-05:00 ERROR Error in Solr batch add. Will retry documents individually at performance penalty: Solr response: 400: {
"responseHeader":{
"status":400,
"QTime":280},
"error":{
"metadata":[
"error-class","org.apache.solr.common.SolrException",
"root-error-class","org.apache.solr.common.SolrException"],
"msg":"ERROR: [doc=9936493910402486] multiple values encountered for non multiValued field title_abbr_tesi: [KEYBOARD THE WORLDS LEADING MUSIC TECHNOLOGY MAGAZINE, Keyboard (Cupertino Calif.)]",
"code":400}}
2021-02-02T12:37:29-05:00 ERROR Could not add record <record #851, source_id:9936493910402486 output_id:9936493910402486>: Solr error response: 400: {
"responseHeader":{ …
=> Bug: Makes title_abbr_tesi multivalued to correct ingestion error.

config/deploy.rb, config/deploy/arch.rb
us-east-1 by default, but arch is (currently) still in us-east-2
=> Updates the AWS region for capistrano

.rubocop.yml, Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/controllers/catalog_controller.rb, app/controllers/search_history_controller.rb, app/models/search_builder.rb, config/routes.rb, lib/marc_indexer.rb, spec/controllers/catalog_controller_spec.rb, spec/system/facet_by_year_spec.rb
- .rubocop.yml: excludes test spec from rubocop rules.
- Gemfile*: adds `blacklight_range_limit` to the application suite.
- app/assets/*, catalog_controller.rb, search_history_controller.rb, search_builder.rb, and routes.rb: integrates `blacklight_range_limit` hooks into the application.
- app/controllers/catalog_controller.rb, lib/marc_indexer.rb, and spec/controllers/catalog_controller_spec.rb: inserts facet and updates sort fields with new field name.
- spec/system/facet_by_year_spec.rb: tests that range limit facet works.
=> Configures Publication/Creation Date facet (#203).

app/controllers/catalog_controller.rb, lib/marc_indexer.rb, spec/controllers/catalog_controller_spec.rb, spec/models/marc_indexing_spec.rb, spec/support/solr_documents/item.rb, spec/system/view_search_results_spec.rb
- app/controllers/catalog_controller.rb: injects `lc_1letter_ssim` into the facet list.
- lib/marc_indexer.rb: pulls multiple values into the needed field.
- spec/*: checks for the correct processing of the facet/field.
=> Configures LOC Classification facet (#202).

.rubocop.yml, HARVESTING_ALMA_DATA.md, README.md, app/services/oai_query_string_service.rb, lib/tasks/marc_index_ingester.rake, spec/models/property_bag_spec.rb, spec/services/oai_query_string_service_spec.rb
- .rubocop.yml: excludes testing and services from rubocop testing.
- HARVESTING_ALMA_DATA.md and README.md: updates instructions on how to index data locally.
- app/services/oai_query_string_service.rb: institutes a service to extract more processing away from the rake task itself.
- lib/tasks/marc_index_ingester.rake: removes logic from rake task and replaces it with a call to the service above.
- spec/*: tests for the correct processing of the query string.
=> Provides option for fully indexing the desired OAI set (#258).

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/blacklight_catalog/_date_slider.scss
- app/assets/stylesheets/blacklight.scss: imports new SCSS partial.
- app/assets/stylesheets/blacklight_catalog/_date_slider.scss: creates a nee SCSS page with styling to make hidden numbers visible.
=> Styles date slider so that dates are visible (#274).

HARVESTING_ALMA_DATA.md, app/services/oai_query_string_service.rb, lib/tasks/marc_index_ingester.rake, spec/services/oai_query_string_service_spec.rb
- HARVESTING_ALMA_DATA.md: updates instructions on how to index one record locally.
- app/services/oai_query_string_service.rb: updates a service to have the ability to re-index one record .
- lib/tasks/marc_index_ingester.rake: adds new parameters for one record re-indexing.
- spec/*: tests for the correct processing of the query string.
=> modifies rake task to re-index a single record

app/controllers/catalog_controller.rb, spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb: removes array of fields and assigns `text_tesi` and `id` to the query fields of Keyword.
- spec/system/targeted_field_search_spec.rb: reworks expectations for Keyword search.
=> Swaps current fields in Keyword search for text_tesi and id (#305).

.rubocop.yml, app/controllers/omniauth_callbacks_controller.rb, app/controllers/omniauth_controller.rb, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/rails_helper.rb
- .rubocop.yml: excludes the spec file from the rubo rules.
- app/controllers/omniauth_callbacks_controller.rb: redirects to page request was made from.
- app/controllers/omniauth_controller.rb: removes logger to increase security.
- spec/controllers/omniauth_callbacks_controller_spec.rb: adds testing for redirects.
- spec/rails_helper.rb: allows mocking of Shibboleth login.
=> Fixes the redirects after login (#318).

app/helpers/render_constraints_helper.rb, app/views/blacklight_range_limit/_range_limit_panel.html.erb, spec/support/shared_examples_for_facet_by_year.rb, spec/system/facet_by_year_spec.rb
- app/helpers/render_constraints_helper.rb: imports helpers used to correct bug on Lux.
- app/views/blacklight_range_limit/_range_limit_panel.html.erb: uses override of blacklight_range_limit's view pulled from Lux.
- spec/support/shared_examples_for_facet_by_year.rb: creates shared examples for repeated testing.
- spec/system/facet_by_year_spec.rb: adds tests to make sure that date_slider and `Unknown` work as expected from the homepage.
=> Fixes bug of no results when using date slider on homepage (#319).

.rubocop.yml, lib/marc_indexer.rb, lib/traject/extract_subject_display.rb, spec/models/marc_indexing_spec.rb
- .rubocop.yml: eliminates the solr marc rake task no longer used.
- lib/marc_indexer.rb: inserts new field, plus connections to its mapping logic.
- lib/traject/extract_subject_display.rb: creates the mapping logic.
- spec/models/marc_indexing_spec.rb: tests expectations for new field.
=> Maps subject_display_ssim with customized logic (#306).

app/models/solr_document.rb, lib/marc_indexer.rb
- app/models/solr_document.rb: eliminates duplicate values on the solr_doc side.
- lib/marc_indexer.rb: passes the denial of alternate script to the mapping.
=> Tweaks the duplication of the vernacular author fields (#310).

lib/traject/extract_author_addl_display.rb, lib/traject/extract_publisher_details_display.rb, spec/models/marc_indexing_spec.rb
- lib/traject/extract_author_addl_display.rb: mimics `extract_marc` method behavior, which iterates over the subfields in the order they appear in the MARC. It was assumed that if we passed `710acb` to the method, it would build a string with the value of "c" after "a"--not so. The letters will act as a pool of subfield codes to test against, which means if the order that the subfields appear is "a", then "b", then "c", it will follow that same order in the retuned string. If we want to restrict the values to a certain order, we have to use the structure I had to alter.
- lib/traject/extract_publisher_details_display.rb: eliminates spacing issues in the values.
=> Corrects bug created by not fully understanding extract_marc method (#314).

lib/marc_indexer.rb, lib/traject/extract_collection.rb, spec/models/marc_indexing_spec.rb
- lib/marc_indexer.rb: tacks on `trim_punctuation` to `author_ssim`.
- lib/traject/extract_collection.rb: calls same method the custom collection method.
- spec/models/marc_indexing_spec.rb: changes the expectation for the custom method response.
=> Adds trim_punctuation to author_ssim and collection_ssim (#357).

app/controllers/catalog_controller.rb, lib/marc_indexer.rb, lib/traject/extract_subject_display.rb, spec/models/marc_indexing_spec.rb
- app/controllers/catalog_controller.rb: swaps out the helper method to the facet search link method.
- lib/marc_indexer.rb and lib/traject/extract_subject_display.rb: trims both string for punctuation.
- spec/models/marc_indexing_spec.rb: resets expectations without punctuation.
=> Converts Genre field to facet search hyperlink (#369).

app/views/catalog/_metadata_block.html.erb, app/views/catalog/_metadata_line.html.erb, app/views/catalog/_url_display.html.erb
This adjusts the column widths on the metadata field labels and content from ".col-3/.col-9" to ".col-4/.col-8"
- app/views/catalog/_metadata_block.html.erb
- app/views/catalog/_metadata_line.html.erb
- app/views/catalog/_url_display.html.erb
=> Adjusts column widths on metadata fields for the show page (#377)

app/controllers/saved_searches_controller.rb
Only added to mimic Penn State's setup, but they eventually removed it anyways.
=> Removes Saved Searches Controller.

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/blacklight_catalog/_more_less.scss, app/helpers/show_page_helper.rb, app/views/catalog/_metadata_block_collapsible.html.erb, app/views/catalog/_show.html.erb, config/locales/en.yml, spec/helpers/show_page_helpers_spec.rb, spec/system/view_show_page_spec.rb
- app/assets/stylesheets/*: inserts the expected text after each collapse action.
- app/helpers/show_page_helper.rb: rearranges the order of where the collapse and overflow links live.
- app/views/catalog/_metadata_block_collapsible.html.erb: reworks block so that the collapse link sits on the bottom and the collapsed items on top of it.
- app/views/catalog/_show.html.erb: alters the partial call to excise the collapse message and add the ability to insert a class into the collapse link.
- config/locales/en.yml: removes the text now inserted via CSS from localization.
- spec/*: reworks expectations to handle new text locations and CSS-injected link text.
=> Refines the show more Title and Authors collapse behavior (#388).

app/helpers/more_options_helper.rb, app/models/solr_document.rb, app/views/catalog/_more_options.html.erb, app/views/catalog/_show_sidebar.html.erb, config/locales/en.yml, spec/helpers/more_options_helper_spec.rb, spec/models/solr_document_spec.rb, spec/system/view_show_page_spec.rb
- app/helpers/more_options_helper.rb: creates a helper to populate the section with the desired links.
- app/models/solr_document.rb: appoints a SolrDocumnet instance method to pull the format_ssim values.
- app/views/catalog/_more_options.html.erb: institutes a partial that stubs the new section.
- app/views/catalog/_show_sidebar.html.erb: overrides the blacklight partial to include the new section.
- config/locales/en.yml: includes the verbiage used in the localizations.
- spec/*: tests and stubs outs expectations for the section.
=> Implements the More Options section of the Show Page (#416).

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/blacklight_catalog/_advanced_search_form.scss, app/controllers/catalog_controller.rb, app/views/advanced/_advanced_search_facets_as_select.html.erb, config/locales/en.yml, lib/marc_indexer.rb, lib/traject/extract_call_number.rb, lib/traject/extract_publication_main_display.rb, lib/traject/extraction_tools.rb, spec/controllers/catalog_controller_spec.rb, spec/models/marc_indexing_spec.rb, spec/system/advanced_search_spec.rb
* This PR is related to #419 
* [Wireframe for adv search form](https://www.figma.com/file/ocSo3KytI6GgwjalSVAmE1/Blacklight-Wireframes?node-id=70%3A272)
* This commit modifies the advanced search form and fields that are being mapped to match requirements.
Advanced search form:
=> Modifies adv search form

app/views/advanced/_advanced_search_form.html.erb, app/views/advanced/_advanced_search_submit_btns.html.erb, app/views/advanced/index.html.erb
* Connected to previous PR around adv-search; the files in this PR need to be overwritten for styling changes to take effect.
=> Overwrites partials from blacklight-adv-search to match styling requirements

config/initializers/prepends.rb, config/prepends/custom_citation_logic.rb, spec/system/view_show_page_spec.rb
- config/initializers/prepends.rb: prepends the new logic to the existing module that serves the citations.
- config/prepends/custom_citation_logic.rb: overrides blacklight 7.4.1 citation method for APA.
- spec/*: tests expectations for the citation title.
=> Generates the correct APA 7th edition citation (#417).

app/helpers/show_page_helper.rb, app/views/catalog/_show_tools.html.erb, spec/helpers/show_page_helpers_spec.rb, spec/system/view_show_page_spec.rb
Connected to: #431 
`app/helpers/show_page_helper.rb` : Adds helper method for constructing direct link
`app/views/catalog/_show_tools.html.erb` : overwrites blacklight partial to include direct link as last item in the list
`spec/helpers/show_page_helpers_spec.rb` : spec for helper method
`spec/system/view_show_page_spec.rb` : feature test spec
This change will require adding a new ENV variable that will identify our host. New ENV variable is `BLACKLIGHT_BASE_URL`
=> Adds direct-link for record in tools menu

app/controllers/catalog_controller.rb, spec/system/view_search_results_spec.rb
Connected to: #440 
`app/controllers/catalog_controller.rb` : Adds index_range for A-Z navigation selection options
`spec/` : Adds spec to demonstrate options show up
=> Adds index_range for A-Z navigation options for facets

app/services/oai_query_string_service.rb, spec/services/oai_query_string_service_spec.rb
- app/services/oai_query_string_service.rb: strips away any possible limitations that could be excluding records from a full (re)index.
- spec/services/oai_query_string_service_spec.rb: updates the expected string returned.
=> Removes all possible restrictions on full indexes (#386).

lib/tasks/marc_index_ingester.rake
lib/tasks/marc_index_ingester.rake: gives priority to `ENV['oai_single_id']` because we're now setting `ENV['oai_set_name']` in the environment variables on the server side and blocks setting `marc_ingext_time` if the indexing is on a single record.
=> Single (Re)Index now doesn't set to_time (#386).

app/assets/javascripts/catalog.js, app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/blacklight_catalog/_print.scss, app/helpers/tools_sidebar_helper.rb, app/views/catalog/_show_request_options.html.erb, app/views/layouts/blacklight/base.html.erb
1. app/assets/javascripts/catalog.js: adds ids into the html that feeds the more/less options.
2. app/assets/stylesheets/blacklight.scss: inserts an import call for the new print partial.
3. app/assets/stylesheets/blacklight_catalog/_print.scss: creates CSS focused solely on the print page.
4. app/helpers/tools_sidebar_helper.rb: changes link to fire off JavaScript's print method.
5. app/views/catalog/_show_request_options.html.erb: provides the wrapping div an id to style it easily.
6. app/views/layouts/blacklight/base.html.erb: inserts the print stylesheet tag to the overridden base page.
=> Implements the Print functionality (#433).

.rubocop.yml, config/prepends/custom_citation_logic.rb
- config/prepends/custom_citation_logic.rb: overrides blacklight 7.4.1 citation method for MLA.
=> Creates custom logic for MLA 8 citations from solr fields

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/blacklight_catalog/_citation.scss, app/views/catalog/_citation.html.erb, config/locales/blacklight.en.yml, spec/system/view_show_page_spec.rb
- app/assets/stylesheets/blacklight.scss and blacklight_catalog/_citation.scss: styles the new citation warning.
- app/views/catalog/_citation.html.erb: overrides the blacklight partial so that the desired warning can be added.
- config/locales/blacklight.en.yml:  localizes the text in the warning.
- spec/system/view_show_page_spec.rb: changes and adds expectations for new warning and layout.
=> Refines the citation modal (#444).

config/locales/blacklight.en.yml
config/locales/blacklight.en.yml: Changes text to reflect the Citation editions.
=> Change the text in the citation modal to reflect editions.

app/controllers/catalog_controller.rb, app/models/concerns/blacklight/solr/document/marc_export.rb, lib/marc_indexer.rb, lib/traject/extract_published.rb
- app/controllers/catalog_controller.rb: changes field name to the newly mapped one.
- app/models/concerns/blacklight/solr/document/marc_export.rb: same as above, but also corrects syntax error.
- lib/marc_indexer.rb: provides customized mapping to the changed field.
- lib/traject/extract_published.rb: logic feeding the mapping.
=> Revises published field to tokenized and ordered mapping (#467).

app/helpers/show_page_helper.rb, app/views/catalog/_direct_link.html.erb, app/views/catalog/_direct_link_modal.html.erb, config/locales/blacklight.en.yml, spec/helpers/show_page_helpers_spec.rb, spec/system/view_show_page_spec.rb
`app/helpers/show_page_helper.rb`: Modifies helper to return link text with doc id instead of creating an href
`app/views/catalog/_direct_link.html.erb`: Adds a modal specific to direct-link (generalized blacklight_modal will not work here).
`app/views/catalog/_direct_link_modal.html.erb`: Adds modal
`config/locales/blacklight.en.yml`: Adds locale for direct link url
`spec/*`: Modifies spec to test new strategy
Note: Please add `ENV['BLACKLIGHT_BASE_URL']` to your env files for deployments. @mlooney @bwatson78 
Eg: `BLACKLIGHT_BASE_URL=https://blackcat-arch.library.emory.edu`
=> Adds modal for direct link url

app/controllers/application_controller.rb, app/models/concerns/blacklight/solr/document/marc_export.rb, app/services/alma_availability_service.rb, app/views/catalog/_show_header.html.erb, app/views/catalog/_show_request_options.html.erb, config/locales/blacklight.en.yml, spec/fixtures/alma_availability_test_file.xml, spec/requests/alma_availability_requests_spec.rb, spec/spec_helper.rb, spec/system/view_show_page_spec.rb
- app/controllers/application_controller.rb: since the availability badge is going dormant at the moment (plans for it on the search results page, this is hijacking the existing availability call for the table's use.
- app/models/concerns/blacklight/solr/document/marc_export.rb: corrects the SolrDocument pull after changes were made on a different ticket.
-  app/services/alma_availability_service.rb: institutes another service method, to focus only on the availability elements/text. Also defines helper methods that serve as logic for which text is delivered.
- app/views/catalog/_show_header.html.erb: strips away the script and span below the main title.
- app/views/catalog/_show_request_options.html.erb: adds a div to have the script deliver needed html for availability.
- …
=> Implements a table for physical availability (#461).

app/services/alma_availability_service.rb, app/views/catalog/_show_request_options.html.erb, config/locales/blacklight.en.yml, spec/requests/alma_availability_requests_spec.rb, spec/system/view_show_page_spec.rb
- app/services/alma_availability_service.rb: incorporates logic needed to determine what should be shown about online items.
- app/views/catalog/_show_request_options.html.erb: adds code to display the online items.
- config/locales/blacklight.en.yml: localizes the text used in the table.
- spec/*: updates and tests the expectations of the table behavior.
=> Adds the online table to the AJAX-delivered Availability diisplay (#462).

app/controllers/catalog_controller.rb, app/views/advanced/_advanced_search_facets_as_select.html.erb, spec/controllers/catalog_controller_spec.rb
- app/controllers/catalog_controller.rb: The advanced search gem's default behavior is to deliver all facets listed in the catalog controller and use each of those facet's limit settings. We, however, are limiting the facets delivered to the 5 currently on the page. If we weren't limiting the facets shown, we could add `'facet.limit' => -1` to the settings hash shown as changed in this pull request, and they'd automatically be unlimited. But, since we're are limiting the fields shown, we have to pass an explicit delimit key/value for each field we'd like to show.
- app/views/advanced/_advanced_search_facets_as_select.html.erb: adds the `data-size` of 6 to all selects on this page.
- spec/controllers/catalog_controller_spec.rb: sets up tests that will fail if any aspect of this …
=> Delimits the facet lists on the Advanced Search page (#473).

app/controllers/catalog_controller.rb, spec/system/view_search_results_spec.rb
* Connected to: #492 
* We are modifying the number of results required for spellcheck suggestions to show up. Previously this was set to 5. This has been changed to zero. Meaning now we will show spellcheck suggestions to the user only if there are no results found. Even if there is one result returned, we will not show suggestions.
Suggestions when no results returned:
No suggestions when at least one result is returned:
=> Modifies spellcheck suggestion requirements

app/controllers/catalog_controller.rb, spec/system/targeted_field_search_spec.rb
* Connected to: #491 
* We are adding `local_call_number_tesim` to query terms list for keyword because this might not always be captured in `text_tesi`.
=> Adds local call number to keyword search query terms

app/views/catalog/_citation.html.erb
=> Removes the Chicago citation from Cite Modal (#509).

app/controllers/catalog_controller.rb, lib/marc_indexer.rb, spec/support/solr_documents/item.rb, spec/system/targeted_field_search_spec.rb, spec/system/view_show_page_spec.rb
- app/controllers/catalog_controller.rb: switches out all string fields to the `_tesim` counterparts.
- lib/marc_indexer.rb: converts one field to multi and creates a doppleganger of another field in text format.
- spec/*: resets expectations for the altered Search Fields.
=> Revise title fields 529

app/models/concerns/blacklight/solr/document/marc_export.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb: fixes punctuation for doi after publisher info
=> fixes punctuation for doi after publisher info for mla 8

app/controllers/catalog_controller.rb, lib/marc_indexer.rb, lib/traject/extraction_tools.rb, spec/support/show_page_value.rb, spec/support/solr_documents/item.rb, spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb: updates field name to the English tokenized version.
- lib/marc_indexer.rb: changes the mapped field so that we have more tokenization options.
- lib/traject/extraction_tools.rb: expands the scope of the field's mapping.
- spec/*: switches the field name to the new one.
=> Revises subject_tsim field (#532).

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
- app/controllers/catalog_controller.rb: removes collection facet from advanced search
- spec/controllers/catalog_controller_spec.rb: removes collection facet from advanced search test
=> suppresses the collections facet on advanced search

app/models/concerns/blacklight/solr/document/marc_export.rb, lib/marc_indexer.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb: removes the current logic to build APA titles and points the new title to a brand new Solr field.
- lib/marc_indexer.rb: maps a new field with everything needed to produce an APA citation title.
=> Revises the title/volume/edition layout of APA citations (#536).

app/helpers/tools_sidebar_helper.rb, app/views/catalog/_feedback.html.erb, spec/system/view_show_page_spec.rb
- app/helpers/tools_sidebar_helper.rb: updates helper method to accept the url from the view call.
- app/views/catalog/_feedback.html.erb: passes the url as argument in the render call.
- spec/system/view_show_page_spec.rb: changes the categorization of a couple of tests and adds a test for the helper.
=>  Modifies the feedback form's url (#544).

lib/traject/extract_publication_date.rb, spec/models/marc_indexing_spec.rb
- lib/traject/extract_publication_date.rb: expands what triggers the logic to kick out to the marc21 method.
- spec/models/marc_indexing_spec.rb: tests the new logic.
=> Fixes indexing errors with pub_date_isim (#558).

app/controllers/catalog_controller.rb, spec/system/sort_results_spec.rb
* **app/controllers/catalog_controller.rb**: Corrects field used for year sorting `pub_date_isim` and secondary sorting field is `title_ssort asc`
* **spec/system/sort_results_spec.rb**: Spec to show the same working
=> Refines year sort oldest, newest

app/controllers/catalog_controller.rb, lib/marc_indexer.rb, spec/system/sort_results_spec.rb, spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb: switches field used for sorting to a `_ssort` ended field. Also uses that new field in the options for sorting.
- lib/marc_indexer.rb: swaps the sort field to the appropriate Solr `_ssort` ending.
- spec/*: updates/adds expectations for field and sorting.
=> Refines the sorting options for Author (#555).

app/services/alma_availability_service.rb, dotenv.sample, spec/requests/alma_availability_requests_spec.rb, spec/services/alma_availability_service_spec.rb, spec/spec_helper.rb, spec/system/alma_request_options_spec.rb, spec/system/view_show_page_spec.rb
- Sane default for ALMA_API_URL
- Alma has different keys for different functions, so specify which API 
key we are using
- This also opens up the application to use further alma apis
- Raise an error if the API key is not set, since the production 
application won't work without it
=> Refactor alma env variables to make production more robust

app/assets/stylesheets/blacklight_catalog/_print.scss, app/assets/stylesheets/blacklight_catalog/_show_page.scss
- app/assets/stylesheets/blacklight_catalog/_print.scss: adds `footer`element to exclusion list.
- app/assets/stylesheets/blacklight_catalog/_show_page.scss: includes the collapsible dts into the same styling as the non-collapsible dts.
=> Adjusts the Print screen styling (#561).

.rubocop.yml, app/assets/stylesheets/blacklight_catalog/_citations.scss, app/helpers/citation_modal_helper.rb, app/views/catalog/_citation.html.erb
- .rubocop.yml: removes the cop for html_safe.
- app/assets/stylesheets/blacklight_catalog/_citations.scss: gives space between citations' headers and text.
- app/helpers/citation_modal_helper.rb: builds out the layout of each type of citation list.
- app/views/catalog/_citation.html.erb: replaces stock logic with call to new helper.
=> Citations sorted by type (#570).

app/assets/stylesheets/blacklight.scss, app/assets/stylesheets/blacklight_catalog/_colors.scss, app/assets/stylesheets/blacklight_catalog/_notifications.scss
- app/assets/stylesheets/blacklight.scss: partializes the css specific to notifications.
- app/assets/stylesheets/blacklight_catalog/_colors.scss: inserts needed colors into partial, as well as forms a mapping of all the colors to be stubbed for notifications.
- app/assets/stylesheets/blacklight_catalog/_notifications.scss: ties color values to the different types of notifications,
`info` 
`success` 
`warning` 
`danger`
default
=>  @bwatson78 Styles the alerts to match notification styles in Pattern Library (#568).

app/assets/stylesheets/blacklight_catalog/_navbar.scss, app/assets/stylesheets/blacklight_catalog/_variables.scss, app/views/shared/_header_navbar.html.erb, app/views/shared/_static_links.html.erb, app/views/shared/_user_util_links.html.erb
- app/assets/stylesheets/blacklight_catalog/_navbar.scss: hides unneeded elements and styles the others.
- app/views/shared/_header_navbar.html.erb: adds the missing links to the right areas, and passes along a class variable making it easier to hide links.
- app/views/shared/_static_links.html.erb: inserts `mobile-only` class into elements that should be hidden on smaller screens.
- app/views/shared/_user_util_links.html.erb: puts a standard link on the mobile view instead of button.
=>  Refines responsive header stying (#574). 

app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/assets/stylesheets/blacklight_catalog/_variables.scss, app/controllers/catalog_controller.rb, app/helpers/search_results_helper.rb, app/views/catalog/_index.html.erb, spec/controllers/catalog_controller_spec.rb, spec/system/view_search_results_spec.rb
- app/assets/stylesheets/blacklight_catalog/_results_list.scss: styles the vernacular title field.
- app/assets/stylesheets/blacklight_catalog/_variables.scss: variable-izes the numeric values.
- app/controllers/catalog_controller.rb: updates the wanted fields on the search results page.
- app/helpers/search_results_helper.rb: copies and modifies the helper method from Show Page.
- app/views/catalog/_index.html.erb: brings in the Blacklight partial to render the vernacular title on the search result list.
- spec/*: updates test expectations.
=>  Revises search results metadata fields shown (#589). 

.rubocop.yml, app/controllers/holding_requests_controller.rb, app/models/holding_request.rb, spec/models/holding_request_spec.rb, spec/requests/holding_req_spec.rb, spec/spec_helper.rb
- Pass in user object rather than only uid when creating holding request
=> Show the request id and pickup library on holding request show page

app/views/catalog/_show_request_options.html.erb, spec/system/view_show_page_spec.rb
One would put this in one's environment, if this gets merged (so then we can swap out easily for production)
```
ALMA_BASE_SANDBOX_URL="https://emory-psb.alma.exlibrisgroup.com"
```
=> Link to Alma services page

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb, spec/system/view_search_results_spec.rb
- app/controllers/catalog_controller.rb: adds the Edition field to search results listing.
- spec/controllers/catalog_controller_spec.rb: updates expectations of the shown metadata fields.
- spec/controllers/catalog_controller_spec.rb: tests that the new field shows on the search results page.
=> Corrects the metadata fields shown in Search Results (#589).

app/controllers/catalog_controller.rb, app/helpers/show_page_helper.rb, spec/helpers/show_page_helpers_spec.rb, spec/support/show_page_value.rb
- app/controllers/catalog_controller.rb: swaps helper methods to newly created function.
- app/helpers/show_page_helper.rb: removes unused iframe method, and creates two methods that form a title query with format facet restriction.
- spec/*: stubs out and tests expectations for new helper method.
https://user-images.githubusercontent.com/18330149/121926021-7ff48e00-cd0b-11eb-96f7-92b1b3305820.mov
=> Refines the title former/later hyperlinks (#618).

app/helpers/catalog_helper.rb, app/helpers/show_page_helper.rb, app/views/catalog/_show_request_options.html.erb, spec/helpers/catalog_helpers_spec.rb, spec/helpers/show_page_helpers_spec.rb
- app/helpers/catalog_helper.rb: removes unused helper, than transfers methods that have more relation to the catalog controller than the show page to this file.
- app/helpers/show_page_helper.rb: removes the methods transferred to the CatalogHelper, and adds the `colonizer` method.
- app/views/catalog/_show_request_options.html.erb: utilizes the new method where the bug was found.
- spec/*: refactors the testing files to match the new homes of the methods, and institutes a new test for the just created helper.
=> Removes colon from library table cell if no subtitle follows (#633).

app/views/devise/sessions/new.html.erb, app/views/static/contact.html.erb
* We are moving the affiliate login button away from the normal login page until we can test the functionality and it is approved.
=> Moves affiliate login button

app/views/advanced/_advanced_search_facets_as_select.html.erb, spec/system/view_show_page_spec.rb
- app/views/advanced/_advanced_search_facets_as_select.html.erb: adds `@response` to accommodate the deprecated behavior warning. 
- spec/system/view_show_page_spec.rb: alleviates the anomaly that the test environment checks the page before CSS styling is applied, while the CI checks it afterwards. Per https://stackoverflow.com/questions/11316249/case-insensitive-rspec-match, checking the body of the page instead of just the rendered page value will return the same in both environments. 
=> Corrects Rspec anomalies.

app/models/concerns/statusable.rb, spec/models/solr_document_spec.rb, spec/system/view_show_page_spec.rb
- app/models/concerns/statusable.rb: adds links to records with AVE fields containing a "u" subfield containing "publishing_base_url".
- spec/*: tests for new expectations.
=> Provide links based on Availability AVE field (#634).

app/models/concerns/statusable.rb, spec/fixtures/alma_request_test_file.xml, spec/models/solr_document_spec.rb, spec/system/view_show_page_spec.rb
First pass just showed 0 or 1 for number of requests, this updates to show real counts by holding_id
=> Show actual number of requests, rather than 0 or 1

app/controllers/hold_requests_controller.rb, app/models/concerns/statusable.rb, app/models/hold_request.rb, app/views/hold_requests/_form.html.erb, spec/fixtures/alma_item_records/22187557270002486.xml, spec/fixtures/alma_multiple_holdings_item_level.xml, spec/models/hold_request_spec.rb, spec/models/solr_document_spec.rb, spec/spec_helper.rb, spec/system/hold_request_spec.rb
Connected to: #682 
* We are adding the ability to request specific items when there's more than one item available for a title. This info is available in the description of the item. Unique item level descriptions are used to tell if an item is unique.
* We are adding a dropdown field that will list the call number and description from which users can choose a particular item to request.
* We are also adding `item_pid` when available to the POST url for create request.
Changes:
**app/controllers/hold_requests_controller.rb:** Adds new param to collect `item_pid`
**app/models/concerns/statusable.rb**: Asks for `item_pid` from item info
**app/models/hold_request.rb**: Adds `item_pid` to POST url if available. Also, adds `items` method to fetch unique items for a title …
=> Adds ability to request at item level

app/models/concerns/statusable.rb, app/models/user.rb, app/services/verification/bus_user_verification_service.rb, app/services/verification/chem_user_verification_service.rb, app/services/verification/hlth_user_verification_service.rb, app/services/verification/illiad_verification_service.rb, app/services/verification/law_user_verification_service.rb, app/services/verification/lsc_user_verification_service.rb, app/services/verification/musme_user_verification_service.rb, app/services/verification/oxfd_user_verification_service.rb, app/services/verification/theo_user_verification_service.rb, app/services/verification/univ_user_verification_service.rb, app/views/catalog/_show_request_options.html.erb, spec/models/solr_document_spec.rb, spec/models/user_spec.rb, spec/system/user_login_spec.rb
- app/models/concerns/statusable.rb: adds method to `solr_document` to determine if it is "deliverable".
- app/models/user.rb: removes method that didn't have sufficient logic.
- app/services/verification/*: institutes methods to determine if holding data permits the user to request document through Illiad.
- app/views/catalog/_show_request_options.html.erb: tying existing link to new logic method. The physical holding is variablized at the top of the partial for faster loading.
- spec/*: tests new methods and refactors others to pass rspec. 
https://user-images.githubusercontent.com/18330149/123712489-68a3bd80-d840-11eb-8fb2-2cc271489df6.mov
=>  Restricts the Request Article to autorized users (#701). 

app/models/concerns/statusable.rb, spec/models/solr_document_spec.rb
If there are over 100 items for a record, pull as many pages as needed to get all the items.
=> Pull all items for a record

app/assets/stylesheets/blacklight_catalog/_buttons.scss, app/assets/stylesheets/blacklight_catalog/_sort_widgets.scss, app/views/catalog/_show_request_options.html.erb
- These styles update in certain situations where the pagination isn't visible, the page title doesn't have enough space between it and the return to search
- Increases width of "where to find it" section title and button
=> Title and sorting margin style fixes (#694)

app/assets/stylesheets/blacklight_catalog/_citations.scss, app/helpers/citation_modal_helper.rb, app/views/catalog/_citation.html.erb, app/views/catalog/_direct_link_modal.html.erb, spec/system/view_show_page_spec.rb
The existing styles that were cleaned up:
- smaller modal titles
- smaller citation titles
- cleaner markup for citations
=> Style modals fixes for citation and direct link

app/views/catalog/_show_request_options.html.erb
Fixes break on smaller screen sizes for "Where to find it" and request button
=> Responsive style widths for "where to find it" title and button (#694)

config/deploy/arch.rb, config/deploy/prod.rb, config/deploy/test.rb, lib/capistrano/tasks/envvars.rake
- config/deploy/*: removes logic pulling ENVs from the local machine and includes call that takes them from the home servers.
- lib/capistrano/tasks/envvars.rake: processes yaml on server side to populate environment variables.
=> Reads ENV vars from server.

app/models/hold_request.rb, app/views/hold_requests/_form.html.erb, spec/models/hold_request_spec.rb, spec/models/user_spec.rb, spec/spec_helper.rb, spec/system/hold_request_spec.rb
* We are changing from the dropdown menu to radio buttons for displaying item level information. This commit also attempts to reduce the number of API calls made on new hold request form.
=> Refactors how holding item information is displayed

app/models/concerns/document_delivery_requestable.rb, app/views/catalog/_show_request_options.html.erb, app/views/catalog/_two_step_illiad_modal.html.erb
Connected to #688 
- Take me an item-level selection page
- Show the call number and description for each item that is available to me based on circulation policy
- When I selected a unique item, take me to ILLiad
- The link to ILLiad request form should be populated with all the available title metadata
=> creates two-step document (ILLiad) request via API

Capfile, Gemfile, Gemfile.lock, app/services/delete_old_guests_service.rb, app/services/delete_old_searches_service.rb, config/schedule.rb, lib/tasks/delete_old_guests_and_associations.rake, spec/services/delete_old_guests_service_spec.rb, spec/services/delete_old_searches_service_spec.rb
* We are adding a rake task with services for deleting old guests and its associations - bookmarks. Searches are also deleted for all null users.
* Rake task is scheduled and added to crontab using whenever.
=> Adds rake task with scheduler for deleting old guests and associations

lib/traject/extract_url_suppl.rb
Connected to #643 
- lib/traject/extract_url_suppl.rb: revises mapping for url_suppl to include blanks
=> revises mapping for url_suppl to include blanks

app/models/concerns/blacklight/solr/document/marc_export.rb, spec/models/solr_document_spec.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb: adds needed extra space before the dash.
- spec/models/solr_document_spec.rb: refactors repetitive code.
=> Bug: corrects the formatting of RIS files to comply with Endnote (#755).

app/views/bookmarks/_clear_bookmarks_widget.html.erb, config/locales/blacklight.en.yml
- app/views/bookmarks/_clear_bookmarks_widget.html.erb: adds needed elements to the Cite link.
- config/locales/blacklight.en.yml: localizes the link text.
=> Corrects the logic to deliver citations on the Bookmark page (#742).

app/assets/stylesheets/blacklight_catalog/_bookmarks.scss, app/assets/stylesheets/blacklight_catalog/_variables.scss
- app/assets/stylesheets/blacklight_catalog/_bookmarks.scss: changes the appearance of the Cite button.
- app/assets/stylesheets/blacklight_catalog/_variables.scss: refactors some of the values of the bookmarks partial into variables.
https://user-images.githubusercontent.com/18330149/126644903-cad49943-c5e3-4c97-ad0e-ce7e4abbd669.mov
=> Refines Bookmark page's cite buton's styling (#775).

app/services/update_collection_authority_service.rb, db/migrate/20210726233825_change_uri_data_type_authority_entry.rb, db/schema.rb
* We don't need to save collection names as a label but only URI. We are saving collection names in URI which is now a text column.
=> Changes URI data type and removes addition of label when saving collections

app/models/concerns/blacklight/solr/document/marc_export.rb, db/schema.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb: swaps out and adds new mappings to the RIS export format.
- db/schema.rb: automatic update to the charset that may need reversing. We'll see after testing completes.
=> Revises and enhances the mapping for RIS export (#779).

app/controllers/collections_controller.rb, app/views/advanced/_advanced_search_facets_as_select.html.erb, config/initializers/advanced_controller.rb, config/routes.rb, config/schedule.rb, lib/tasks/marc_index_ingester.rake, spec/controllers/collections_controller_spec.rb
* We are trying to improve the collection filter on the advanced search page. We will only be showing the first 100 collection names but will make the entire table searchable by using ajax GET requests.
**app/controllers/collections_controller.rb**: New collections search controller. We are using LIKE sql query.
**app/views/advanced/_advanced_search_facets_as_select.html.erb**: Adds simple ajax call to the collections search controller action
**config/initializers/advanced_controller.rb**: Limits dropdown to only first 100 options
**config/routes.rb**: Updates route for new controller
**config/schedule.rb**: Adds whenever schedule to run service at 3am every night
=> Attempts to improve collection filter

app/views/shared/_header_navbar.html.erb, app/views/shared/_static_links.html.erb, config/locales/blacklight.en.yml
- app/views/shared/_header_navbar.html.erb: changes main page title header and link, and localizes the other text on this element.
- app/views/shared/_static_links.html.erb: updates the About link text, as well as localizes the other links' text.
- config/locales/blacklight.en.yml: establishes the localized text used in the previous partials.
=>  Updates the text and links of the header logos and links (#798). 

app/controllers/collections_controller.rb, app/views/advanced/_advanced_search_facets_as_select.html.erb
* We will now wait for user to type at least three letters before we begin searching. We are also limiting number of results returned in an attempt to not freeze the search. Finally, we are only looking for options where typed letters are beginning of words.
=> Attempts to improve col filter even more

app/views/advanced/_advanced_search_facets_as_select.html.erb
app/views/advanced/_advanced_search_facets_as_select.html.erb: inserts quotes into the JS to stringify the values.
Since this is a quick fix and POs are awaiting this correction, I have forgone Rspec since it was showing signs that it would take until next day to figure it out.
=> Bug: Corrects the values being used as data attributes in the option injection (#808).

app/models/concerns/blacklight/solr/document/marc_export.rb, lib/marc_indexer.rb
- app/models/concerns/blacklight/solr/document/marc_export.rb: removes two mappings marked for deletion and swaps author field to the that doesn't scrape the relator field.
- lib/marc_indexer.rb: excises geocode from the `publisher_location_ssim` field.
=> Refines RIS output via mapping changes (#811).

app/models/concerns/blacklight/solr/document/marc_export.rb
app/models/concerns/blacklight/solr/document/marc_export.rb: removes DA, which seemed to have created conflicts with Endnote, and swaps out solr field feeding the main author value.
=> Additional RIS mapping changes (#811).

lib/traject/extract_title_main_first_char.rb
lib/traject/extract_title_main_first_char.rb: utilizes Marc21's built in processing to eliminate non-filing words from titles, giving this field the true first character.
=> Eliminates non-filing words from the First Char solr field processing (#813).

lib/marc_indexer.rb, lib/traject/extract_emory_sortable_author.rb, lib/traject/extract_emory_sortable_title.rb, lib/traject/extract_title_main_first_char.rb, lib/traject/extraction_tools.rb, spec/controllers/sessions_controller_spec.rb, spec/models/marc_indexing_spec.rb
- lib/marc_indexer.rb: adds two new customized extraction methods that strip punctuation out of the title/author sorts.
- lib/traject/*: institutes code to extract punctuation.
- lib/traject/extract_title_main_first_char.rb: swaps out long call to module with a new method.
- lib/traject/extraction_tools.rb: inserts two new methods that DRY up the other module's processes.
- spec/*: changes and inserts new expectations.
=> Removes punctuation from Title and Author sort fields (#814).

lib/traject/extract_title_main_first_char.rb, spec/fixtures/alma_marc_resource.xml, spec/models/marc_indexing_spec.rb
- lib/traject/extract_title_main_first_char.rb: checks for match before pushing to accumulator.
- spec/fixtures/alma_marc_resource.xml: changes title for testing purposes.
- spec/models/marc_indexing_spec.rb: tests new protective logic.
=> Bug: main title first char mapping error.

config/locales/blacklight.en.yml, spec/system/targeted_field_search_spec.rb
- config/locales/blacklight.en.yml: overrides blacklight localization.
- spec/system/targeted_field_search_spec.rb: tests for the right verbiage.
=> Changes the placeholder text in the Search bar (#837).

app/views/catalog/_show_request_options.html.erb, spec/system/hold_request_spec.rb, spec/system/view_show_page_spec.rb
- app/views/catalog/_show_request_options.html.erb: comments out Request button code.
- spec/*: exits out of Request button tests.
=> Hides the Request button on the single item view page (#836).

.rubocop.yml, lib/traject/extract_publication_date.rb, spec/fixtures/alma_marc_resource.xml, spec/models/marc_indexing_spec.rb
- .rubocop.yml: escapes file from the rubocop rules for complexity.
- lib/traject/extract_publication_date.rb: reworks and refactors mapping of pub_date_isim.
- spec/*: refactors and tests new expectations.
=> Adjusts how indexer handles zeroes in 008 (#839).

app/controllers/catalog_controller.rb, spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb: inserts `other_standards_ids_tesim` into the keyword search list.
- spec/system/targeted_field_search_spec.rb: checks that the keyword search is finding results from that field.
=> Adds other_standards_ids_tesim to Keyword Search (#855).

app/assets/stylesheets/blacklight_catalog/_facets.scss
the "archival materials/manuscripts" is no longer breaking randomly
=> adds word-wrap style to prevent weird breaking in facets per task 858

lib/traject/extraction_tools.rb, spec/fixtures/alma_marc_resource.xml, spec/models/marc_indexing_spec.rb
- lib/traject/extraction_tools.rb: changes text to desired format.
- spec/fixtures/alma_marc_resource.xml: updates the format of two records to output the new verbiage in new tests.
- spec/models/marc_indexing_spec.rb: tests for new verbiage.
=> Updates format verbiage (#884)

app/views/catalog/_title_starts_with_index.html.erb, app/views/layouts/blacklight/base.html.erb, spec/system/view_search_results_spec.rb
- app/views/catalog/_title_starts_with_index.html.erb: corrects the limiter for when this partial is delivered.
- app/views/layouts/blacklight/base.html.erb: removes limiter from render call since it's not needed.
- spec/system/view_search_results_spec.rb: tests for correct behavior.
=> Bug: Title Starts With doesn't appear when facet chosen from homepage (#892).

app/helpers/search_results_helper.rb, spec/system/view_search_results_spec.rb
- app/helpers/search_results_helper.rb: merges instead of replacing to ensure other facets stay in place.
- app/helpers/search_results_helper.rb: tests to ensure previous facets remain when choosing a Title Starts With letter.
=> Bug: Title Starts with clears previous facets fix (#890).

app/helpers/more_options_helper.rb, config/application.rb, lib/traject/extraction_tools.rb, spec/helpers/more_options_helper_spec.rb
- app/helpers/more_options_helper.rb: utilizes the constant created in the indexing method to feed the links hash.
- config/application.rb: loads the traject methods so that `MARC_RESOURCE_FORMATS` is readable elsewhere.
- lib/traject/extraction_tools.rb enforces the defining and pulling of each format's text to one place.
- spec/helpers/more_options_helper_spec.rb: ties tests to the one source of truth.
=> BUG FIX: updates defining of Marc Resource format text (#968).

app/assets/javascripts/catalog.js, app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/controllers/availability_indicators_controller.rb, app/services/alma_availability_service.rb, app/views/catalog/_availability_indicator.html.erb, app/views/catalog/_index.html.erb, app/views/catalog/_search_results.html.erb, config/initializers/catalog_index_override.rb, config/routes.rb, spec/system/view_search_results_spec.rb
Changes include:
- Remove ALMA availability request from page load
- Add loading indicator on page load for Access & Availability information
- Add `AvailabilityIndicatorsController` which renders views of availability indicators for any documents requested. The controller returns a JSON with key as the document ID and value as the view html in string format.
- Add ajax request to `AvailabilityIndicatorsController` to replace loading indicators with availability indicators after page load
Please refer to the following recording for UI changes in this PR:
https://user-images.githubusercontent.com/13107510/139339745-c5a619d7-e4e9-42df-be5f-3c82846f82fb.mov
=> #981 Get alma availability after page load

app/views/static/contact.html.erb, app/views/static/contact/_assistance.html.erb, app/views/static/contact/_assistance_link.html.erb, app/views/static/contact/_card_link_li.html.erb, app/views/static/contact/_explore_card.html.erb, config/locales/en.yml
All: adds target: blank to the link requested, but also refactors the page to point to sections of the page.
=> Revises feedback link to open in new tab/window (#1001).

.gitignore, app/views/catalog/_facet_group.html.erb, app/views/catalog/_show.html.erb, app/views/layouts/application.html.erb, app/views/layouts/blacklight/base.html.erb, dotenv.sample
- .gitignore: ruby version seems to be generating in the app now, so I'll avoid sending it to github.
- app/views/catalog/_facet_group.html.erb: institutes Google tagging that (the first two) reports when a facet limiter is enforced, and also reports when a facet collapsible is clicked.
- app/views/catalog/_show.html.erb: tags the document's library and format.
- app/views/layouts/*: mimics Lux' setup that places the script in both base and application's erbs.
- dotenv.sample: calls out needed new ENV.
Behind the scenes, no screenshots needed.
=> Integrates Google Analytics into the catalog (#667). 

app/controllers/application_controller.rb
Per @rotated8's recommendation, I am enabling app profiling for all users for all environments except the production instance.
=> Enable app profiling for all environments except production instance

app/controllers/catalog_controller.rb, spec/system/targeted_field_search_spec.rb
- app/controllers/catalog_controller.rb: creates a array variable for the keyword fields, which has the new fields and their boosting values.
- spec/system/targeted_field_search_spec.rb: updates the expectations for the search results tests.
=> Boosts select fields in the Keyword option (#1034).

app/assets/stylesheets/blacklight_catalog/_navbar.scss, app/views/shared/_beta_banner.html.erb, app/views/shared/_header_navbar.html.erb
- app/assets/stylesheets/blacklight_catalog/_navbar.scss: styling for banner.
- app/views/shared/_beta_banner.html.erb: banner html.
- app/views/shared/_header_navbar.html.erb: render call to banner.
=> Adds banner to homepage announcing beta (#1059).

app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/assets/stylesheets/blacklight_catalog/_variables.scss
- app/assets/stylesheets/blacklight_catalog/_results_list.scss: swaps to a new variable pointing directly to this value.
- app/assets/stylesheets/blacklight_catalog/_variables.scss: creates variable for the new value.
=> Reduces the results headers' font size (#1085).

app/assets/stylesheets/blacklight_catalog/_colors.scss, app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/helpers/search_results_helper.rb, app/services/alma_availability_service.rb, spec/services/alma_availability_service_spec.rb, spec/spec_helper.rb
- app/assets/*: adds the needed badge color.
- app/helpers/search_results_helper.rb: updates logic to deliver the new badge.
- app/services/alma_availability_service.rb: provides a new hash attribute that points to existing holdings with the `check_holdings` availability status.
- spec/*: adds a test to make sure the AlmaAvailabilityService tests for `check_holdings` correctly.
=> Adds Check Holdings as an availability indicator (#1051).

app/views/catalog/_show_request_options.html.erb, config/initializers/catalog_show_override.rb, spec/system/view_show_page_spec.rb
Restore request dropdown that allows users to submit hold requests using the ALMA API, as well as "Request Article or Chapter" and "Request from Special Collections". The feature is still being the feature toggle `enable_requesting_using_api`. This is a feature intended for v2 of the Blacklight catalog project.
=> Restore submitting holds requests using the ALMA API

app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/controllers/catalog_controller.rb, app/helpers/availability_helper.rb, app/helpers/catalog_helper.rb, app/helpers/search_results_helper.rb, app/services/alma_availability_service.rb, app/views/catalog/_availability_indicator.html.erb, app/views/catalog/_show_request_options.html.erb, app/views/catalog/_sort_and_per_page.html.erb, app/views/catalog/availability/_badges.html.erb, app/views/catalog/availability/_table.html.erb, spec/controllers/catalog_controller_spec.rb, spec/services/alma_availability_service_spec.rb, spec/system/bookmarks_page_spec.rb, spec/system/view_search_results_spec.rb, spec/system/view_show_page_spec.rb
- app/assets/stylesheets/blacklight_catalog/_results_list.scss: corrects style of surrounding elements for new table.
- app/controllers/catalog_controller.rb: removes call number display in both show and index.
- app/helpers/availability_helper.rb: institutes another helper module to group methods into a more precise use case.
- app/helpers/catalog_helper.rb: swaps hash test to new key.
- app/helpers/search_results_helper.rb: extracts methods to a more aptly named module.
- app/services/alma_availability_service.rb: refactors class to reduce size of method and includes new logic that iterates over multiple `AVA` fields.
- app/views/catalog/_availability_indicator.html.erb and app/views/catalog/_show_request_options.html.erb: removes repeated html and calls newly created partials.
- …
=> Reworks Availability Sections (#1096).

app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/models/solr_document.rb, app/views/catalog/availability/_badges.html.erb
- app/assets/stylesheets/blacklight_catalog/_results_list.scss: styles badges.
- app/models/solr_document.rb: provides presence of bound with test.
- app/views/catalog/availability/_badges.html.erb: adds logic and html to deliver badge and link.
=> Creates service page link for no physical items but bound with (#1097).

Gemfile, app/controllers/application_controller.rb, config/application.rb
After changes made to speed up the index page, we no longer need app profiling in Test and Arch.
=> Restrict app profiling to development environment

app/views/catalog/_marc_view.html.erb
=> Includes field 940 into librarian view (#1115).

app/controllers/catalog_controller.rb, spec/system/view_search_results_spec.rb
- app/controllers/catalog_controller.rb: sets to negative one, effectively turning off suggestions.
- spec/system/view_search_results_spec.rb: changes expectations to not seeing suggestions.
=> Removes the spellcheck suggestions from blank search result (#1119).

app/controllers/catalog_controller.rb, app/views/catalog/_facet_group.html.erb, spec/controllers/catalog_controller_spec.rb, spec/system/view_search_results_spec.rb
- app/controllers/catalog_controller.rb: creates a config variable containing solr fields that shouldn't be displayed in facet group, and adds facet field `author_display_ssim` to tweak the label.
- app/views/catalog/_facet_group.html.erb: points the suppressed fields array to the config variable for ease of future suppression.
- spec/*: sets expectations for new field suppression.
=> Replaces Author limiter label with more appropriate verbiage (#1134).

app/views/catalog/availability/_badges.html.erb
Adds the presence of bound with field as holdings available
.
=> Refines the Contact Us availability badge display logic (#1097).

.rubocop.yml, app/views/catalog/_home_text.html.erb, app/views/layouts/blacklight/base.html.erb, config/initializers/catalog_index_override.rb, spec/system/ejournals_spec.rb
- .rubocop.yml: skips method length rule for catalog controller override.
- app/views/catalog/_home_text.html.erb: adds overlay html for empty results redirect.
- app/views/layouts/blacklight/base.html.erb: gives proper spacing to the logic wrapped render calls.
- config/initializers/catalog_index_override.rb: redirests to an empty search when documents list is empty.
- spec/system/ejournals_spec.rb: removes expectations for constraint buttons since the redirect won't have them.
=> Redirects to a blank search results page with overlay when search returns nothing (#1146).

.rubocop.yml, lib/traject/extract_url_fulltext.rb, lib/traject/extract_url_suppl.rb, spec/models/marc_indexing_spec.rb
Refer to the requirements below:
Revise mappings for the following:
`url_fulltext_ssm`: Include the current logic, but **exclude** the following:
If `ind2=0 or 1` and exactly matches one of these strings in `$3`, `$y,` or `$z`:
```
Table of contents
Table of contents only
Publisher description
Cover image
Contributor biographical information
```
`url_suppl_ssim`: Include the current logic, plus **include** 856s with `ind2=0 or 1` that contain exact matches on the strings listed previously.
```
Table of contents
Table of contents only
Publisher description
Cover image
Contributor biographical information
```
Note: we don't want to use a "contains" type logic here because sometimes a phrase like "table of contents" may be part of a longer phrase such as "Full text including table of …
=> Revise marc 856 mappings

app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/views/catalog/availability/_table.html.erb
Refer to the screenshots below:
=> Refine availability table css

app/assets/stylesheets/blacklight_catalog/_results_list.scss
- Reduce table headers font size to 0.875rem
- Increase bottom margin of article.document > dl.row > dd to 6px on mobile
=> CSS refinements for availability table

app/models/oai_validation/deactivated_portfolios_rule.rb, app/models/oai_validation/deleted_records_rule.rb, app/models/oai_validation/lost_stolen_records_rule.rb, app/models/oai_validation/rule.rb, app/models/oai_validation/suppressed_records_rule.rb, app/models/oai_validation/temporary_located_records_rule.rb, app/services/oai_processing/oai_processing_toolset.rb, app/services/oai_processing_service.rb, app/services/oai_validation_service.rb, spec/services/oai_validation_service_spec.rb
- Add new model `OaiValidation::Rule` to represent a generic validation rule and all its methods
- Add a new model that inherits from `OaiValidation::Rule` for each validation rule currently used in the ingest process
- Edit `OaiValidationService` to use the new rules for validation
- Edit `OaiProcessingService` to use the new rules for validation and indexing
The main aim of this PR is to split current indexing deletion/suppression rules into individual rules, and have the rules be reusable across the app. The newly introduced `OaiValidation::Rule` has to useful methods, `#records_ids` and `#apply`. `#records_ids` returns all record ids affected by the rule in the `document`, and `#apply` applies the requirements of the rule on the document. For example, for …
=> Add OAI Validation Rule model

app/assets/stylesheets/blacklight_catalog/_print.scss, app/assets/stylesheets/blacklight_catalog/_results_list.scss, app/views/catalog/availability/_table.html.erb
Fixes #1216 
This PR addresses the following issue reported by @eporter23:
> @abelemlih looks much better in all the various views, thank you! I am still seeing an outline for the hidden availability column in Safari and Firefox, though it is fine in Chrome
**View**:
**Print output in Chrome**:
**Print output in Firefox**:
**Print output in Safari**:
=> Fix availability table layout for printing

app/views/devise/shared/_links.html.erb
Fixes #1040
Background: When I first read the if statement that determines what path to assign to a login link, I was confused because both the if and else scenarios labeled the link `Emory Users Login`, meaning for any other provider than `shibboleth`we still name it `Emory Users Login`. Upon further inspection, I figured that the if statement is supposed to set `Emory Users Login` when the provider is `shibboleth`, and name any other login link based on the provider's name. The changes in this PR ensure the if/statement renders the correct label and path for a login link based on the provider.
=> Refactor login links view

app/helpers/exterior_links_helper.rb, app/views/catalog/_index.html.erb, app/views/catalog/availability/_badges.html.erb
- app/helpers/exterior_links_helper.rb: changes the method to dynamically add force direct command when needed and refactors another method.
- app/views/catalog/_index.html.erb: removes an unused variable.
- app/views/catalog/availability/_badges.html.erb: makes online badge button force directed.
No visual changes, no screenshots.
=> Skips the service page for online links.

app/helpers/more_options_helper.rb, spec/helpers/more_options_helper_spec.rb
- app/helpers/more_options_helper.rb: changes the destinations of the materials' mappings.
- spec/helpers/more_options_helper_spec.rb: updates the expectations of the tests.
Mostly backend changes, no screenshots necessary.
=> Points the Find More.. links to new Drupal homepage (#1249).

config/locales/blacklight.en.yml, spec/system/view_show_page_spec.rb
=> Changes the Harmful Language Tools link text (#1233).

app/views/catalog/show.xml.builder, config/initializers/catalog_show_override.rb, spec/system/view_show_page_spec.rb
- app/views/catalog/show.xml.builder: stubs out template to build XML document for Ares.
- config/initializers/catalog_show_override.rb: ensures that the .xml extension looks at the builder template.
- spec/system/view_show_page_spec.rb: tests the expectations of the XML.
```
<?xml version="1.0" encoding="UTF-8"?>
<document>
<title>Arntz-Bulletin; : Dokumentation der Kunst des 20. Jahrhunderts. Bibliographie, Werk-Kataloge ...</title>
<author/>
<edition/>
<publisher>[Distributed in U.S. by Wittenborn, Verlag G. Arntz-Winter]</publisher>
<publication_date>1968</publication_date>
<isbn/>
<issn/>
<holdings>
<holding>
<barcodes type="multi-value" delim="|">010000712412|010000712414</barcodes>
<volumes_issues type="multi-value" delim="|">V.1|V.2 PT.1-6</volumes_issues>
<call_number>Z5935 …
```
=> Creates XML template to pass to Ares (#1131).

.rubocop.yml, app/views/catalog/_facet_group.html.erb, app/views/catalog/_search_form.html.erb, app/views/catalog/_title_starts_with_index.html.erb, app/views/layouts/blacklight/base.html.erb, app/views/shared/_header_navbar.html.erb, config/initializers/catalog_index_override.rb, spec/system/front_page_spec.rb
- .rubocop.yml: excludes the override of CatalogController's index method.
- app/views/*: uses newly created instance variable to feed homepage verification.
- config/initializers/catalog_index_override.rb: updates excluded params with `_ga` and provides that test result to the view.
- spec/system/front_page_spec.rb: makes sure visiting `/?_ga=2.254463560.1947920273.1649182547-1700922359.1649079393` produces the same results as the homepage.
=> Ignores the Google Analytics param coming from Drupal (#1255).

app/views/catalog/_physical_holding.xml.builder, app/views/catalog/_supplemental_link.xml.builder, app/views/catalog/show.xml.builder, spec/system/view_show_page_spec.rb
- app/views/catalog/_physical_holding.xml.builder: throws enumerative code into a partial. Also breaks out items into their own element with associative barcode, vol/issue, and status.
- app/views/catalog/_supplemental_link.xml.builder: a partial created for the requested supplemental links addition.
- app/views/catalog/show.xml.builder: 
- Adds the holding type boolean elements.
- Points to the partial above for the supplemental links.
- Partializes the holdings elements and also renames them since we are now referring to online resources.
- spec/system/view_show_page_spec.rb: Updates the spec to expect the new elements and structure.
=> Adds requested elements to a Record's show XML.

lib/marc_indexer.rb, spec/fixtures/alma_marc_resource.xml, spec/models/marc_indexing_spec.rb
- lib/marc_indexer.rb: ensures that 022a and 022y are separate values in the Solr mapping. 
- spec/fixtures/alma_marc_resource.xml: adds a 022 datafield to test against.
- spec/models/marc_indexing_spec.rb: verifies that the separate subfields come through as more than one value.
=> Separates the values for 022ay to make searching easier (#1260).

app/services/oai_query_string_service.rb, spec/services/oai_query_string_service_spec.rb
- app/services/oai_query_string_service.rb: adds blocker to resumption token query if single_record is present.
- spec/services/oai_query_string_service_spec.rb: checks for right results.
=> Process a single record index regardless of presence of resumption token.

app/views/shared/_header_navbar.html.erb
app/views/shared/_header_navbar.html.erb: comments out rendering of banner.
=> Removes Illiad downtime banner.

app/models/concerns/statusable.rb, app/views/catalog/_physical_holding.xml.builder, spec/models/solr_document_spec.rb, spec/system/view_show_page_spec.rb
- app/models/concerns/statusable.rb: widens out the scope of the item value scraping, and adds the temporary details needed.
- app/views/catalog/_physical_holding.xml.builder: removes copy number and adds in item specific library and location with logic to read temporarily located records.
- spec/*: updates expectations for new and removed keys/values.
=> Factors in logic that shows temporarily located items.

app/models/concerns/statusable.rb, app/views/catalog/SHOW_XML_README.md, app/views/catalog/_physical_holding.xml.builder, app/views/catalog/show.xml.builder, spec/models/solr_document_spec.rb, spec/system/view_show_page_spec.rb
- app/models/concerns/statusable.rb: Ares wants codes, so updating the values to the inner text instead of the description attribute.
- app/views/catalog/SHOW_XML_README.md: institutes a readme for the values pulled for XML document.
- app/views/catalog/_physical_holding.xml.builder: switches out to value to pull the desired code.
- app/views/catalog/show.xml.builder: adds the newly requested physical description.
- spec/*: updates the expectations to reflect the new changes.
Example document shared in Slack.
=> Creates a record XML's reference doc and updates values (#1278).

app/views/static/about.html.erb, config/locales/en.yml, spec/system/view_about_page.rb
- app/views/static/about.html.erb: now pointing to `/help`.
- config/locales/en.yml: updates text to the Help & Contacts page.
- spec/system/view_about_page.rb: institutes a needed test.
=> Removes old links back to Contacts page.

Gemfile, Gemfile.lock, app/controllers/admin/admin_controller.rb, app/controllers/admin/application_controller.rb, app/controllers/admin/content_blocks_controller.rb, app/controllers/admin_controller.rb, app/dashboards/content_block_dashboard.rb, app/models/ability.rb, app/models/content_block.rb, app/views/admin/admin/index.html.erb, app/views/admin/content_blocks/_form.html.erb, app/views/shared/_beta_banner.html.erb, app/views/shared/_header_navbar.html.erb, app/views/shared/_homepage_banner.html.erb, app/views/shared/_user_util_links.html.erb, config/routes.rb, db/migrate/20220711210400_create_content_blocks.rb, db/migrate/20220714215552_add_homepage_banner_content_block.rb, db/schema.rb, spec/controllers/admin/admin_controller_spec.rb, spec/controllers/admin/content_blocks_controller_spec.rb, spec/factories/content_blocks.rb, spec/features/admin_dashboard_spec.rb, spec/features/content_blocks_dashboard_spec.rb, spec/models/content_block_spec.rb
This PR addresses the following requirement from #1275:
- Add admin ability to edit front page banner
This PR includes the following changes:
- Add gem `administrate ` to use customizable admin dashboards
- Add a dashboard to display and edit content blocks under route `/admin/content_blocks`
- Only allow logged in admins to read and update content blocks, no user is allowed to delete a content block
- Use value of `ContentBlock.homepage_banner` to populate the homepage banner, and remove deprecated view `_beta_banner.html.erb`
Please refer to the following screenshots:
=> Add content blocks admin dashboard

lib/traject/extract_marc_resource.rb, lib/traject/extraction_tools.rb, spec/fixtures/alma_marc_resource.xml, spec/models/marc_indexing_spec.rb
- lib/traject/extract_marc_resource.rb: removes "not indicator2 == 2" logic and uses the reworked method to determine fulltext links.
- lib/traject/extraction_tools.rb: the reworked supplemental text values.
- spec/fixtures/alma_marc_resource.xml: adds in new testing values.
- spec/models/marc_indexing_spec.rb: adds in tests, but also removes a test that is no longer valid:
- "and 000/6 == e, f, g, k, o, or r and 008/29 != o or s": this now gets a Online status, which negates the At Library logic.
=> Reintroduce the marc_resource logic reverted earlier (#1273).

.rubocop.yml, app/models/concerns/blacklight/solr/document/marc_export.rb, lib/chicago_citation_formatter.rb, lib/citation_string_processor.rb
Fixes #961
The following are the issues raised by @eporter23 and a screenshot that corresponds to the fix for each error:
**Record**
> This record shows DOI but actually is another type of identifier (we only want a DOI entry, which is one of several types of standard identifiers). The author entry also shows ", and author". https://blackcat-test.library.emory.edu/catalog/9937313645402486
**Fix**
**Record**
Here is another example of the ", and author" being added. It looks like the $e relator term is getting included, which we don't want. https://blackcat-test.library.emory.edu/catalog/990035853090302486
**Fix**
**Record**
> This record is missing the publication information: https://blackcat-test.library.emory.edu/catalog/990018128730302486
**Fix**
**Record**
This record omits the …
=> Add enhancements to Chicago citation formatter

Gemfile, Gemfile.lock
Fixes `Not found. Authentication passthru.` error in the authentication worflow.
Refer to https://github.com/emory-libraries/dlp-curate/pull/2034 and https://github.com/emory-libraries/dlp-curate/pull/2038 for details on the fix we implemented in `dlp-curate`
=> Revert omniauth upgrade

app/models/concerns/statusable.rb, app/views/catalog/show.xml.builder, spec/fixtures/alma_availability_test_file_a.xml, spec/fixtures/alma_item_records/990005988630302486.xml, spec/system/view_show_page_spec.rb
- app/models/concerns/statusable.rb: 
- creates a customized method especially for the XML physical holdings
- wires the pulling of holding items to accommodate missing holding ids.
- app/views/catalog/show.xml.builder: uses the new modified method instead.
- spec/*: tests presence of the new temp located item.
=> Fixes the bug preventing temporarily located items from appearing in a record's XML.

Gemfile, Gemfile.lock
Update blacklight to v7.4.2 to resolve Honebadger issues [#83159596](https://app.honeybadger.io/projects/90760/faults/83159596) and [#83683134](https://app.honeybadger.io/projects/90760/faults/83683134).
This issue has been resolved in Blacklight `v7.4.2`. Please refer to the following in the release [details](https://github.com/projectblacklight/blacklight/releases/tag/v7.4.2):
> Make sure #display_type always return an array (https://github.com/projectblacklight/blacklight/pull/2218)
=> Update blacklight to v7.4.2

app/controllers/availability_indicators_controller.rb, app/views/catalog/_show.html.erb, app/views/catalog/_show_request_options.html.erb, app/views/catalog/show_tools/_metadata_block.html.erb, config/initializers/catalog_show_override.rb, config/routes.rb
- app/controllers/availability_indicators_controller.rb: adds a controller action to pull just a single document's availability and deliver it via partial.
- app/views/catalog/_show.html.erb: provides a container for the partial instead of directly loading it, and adds AJAX to call the partial GET path.
- app/views/catalog/_show_request_options.html.erb: reworks this partial to utilize the new variables coming from the just created action. Also adds script to open the show pages availability immediately.
- app/views/catalog/show_tools/_metadata_block.html.erb: removes the exand command that wasn't working in this position anymore.
- config/initializers/catalog_show_override.rb: Strips API reliant pulls from the Controller function.
- config/routes.rb: adds another route to the …
=> Makes show page's availability async.

app/models/oai_validation/deleted_records_rule.rb, spec/spec_helper.rb
- app/models/oai_validation/deleted_records_rule.rb: since the `ListRecord` OAI api interface has shown old information when it comes to status, we have to incorporate the seemingly updated `GetRecord` status into the indexing process.
- spec/spec_helper.rb: adds more stubs to accommodate the additional API calls.
=> Adds extra deletion validation that pulls an ID's GetRecord.

app/views/catalog/availability/_table.html.erb, lib/traject/extract_url_fulltext.rb, lib/traject/extract_url_suppl.rb
Fixes #1319 
- Search results no longer show sample text
- Item page shows sample text under "Related Resources Link"
=> Revise 856 mapping

app/services/delete_old_guests_service.rb, app/services/delete_old_searches_service.rb, config/schedule.rb, spec/services/delete_old_guests_service_spec.rb, spec/services/delete_old_searches_service_spec.rb
Previously, this ran every 30 minutes, and did not seem to complete in a reliable way. This should attempt to run less frequently, and report start and end times when it finishes.
=> Delete guest users and searches once a day

app/views/catalog/other_resources/_accordions.html.erb
per https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/23
=> AS023: Updates the link url for Finding Aids to archives.libraries.

app/helpers/alternate_catalog_helper.rb, app/views/shared/_header_navbar.html.erb
- Add empty `alt` to lightbulb picture in the homepage since it is decorative
- Add `aria-label` to homepage Emory Library logo/link that takes the user back to the catalog homepage
=> Address Lighthouse report warnings

spec/models/marc_indexing_spec.rb
Rather than needing to update tests each January as the year changes, use the Date module to get the current year programmatically.
=> Automates current year testing

Gemfile, Gemfile.lock, config/initializers/advanced_controller.rb, lib/tasks/marc_index_ingester.rake
Fix #1389 
In this PR, I use static page caching to cache the advanced search index page, which has Solr data that is only updated once we run a full or incremental reindex. The cache will be recreated every time:
- An incremental reindex is processed
- A full reindex is processed
- A new version is deployed, since the cache is stored in the public folder which gets reset upon deployment
=> Cache advanced search index page

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
Fix #1387
The show page has links for fields such as "Additional Author/Creators" that lead users to running a facet search (e.g. using field `author_add_ssim`) without the field being explicitly set as a facet field in the Blacklight configuration.
In this PR, I added all fields that are used as facet fields on links on the show page to the Blacklight configuration as facet fields. This resolves the issue reported in #1387.
=> Blacklight 7.33 Upgrade: Fix facet search from links on show page

app/helpers/blacklight_advanced_search/advanced_helper_behavior.rb, app/views/advanced/_advanced_search_facets_as_select.html.erb, app/views/advanced/_collection_select.html.erb, config/initializers/advanced_controller.rb, lib/tasks/marc_index_ingester.rake
- Disable caching the advanced search page
- Override `app/helpers/blacklight_advanced_search/advanced_helper_behavior.rb` to initialize and use one query parser to check if a facet value is checked,  refer to method `def facet_value_checked?`
- Change advanced search facet views to use facet label directly instead of using `#facet_display_value`. The use of `facet_display_value` leads to a massive number of allocations when the field rendered has a lot of values.
- Remove advanced search page caching related logic from indexing
=> Disable advanced search page caching

app/helpers/blacklight_advanced_search/advanced_helper_behavior.rb, app/views/advanced/_advanced_search_facets_as_select.html.erb, app/views/advanced/_collection_select.html.erb, config/initializers/advanced_controller.rb, lib/tasks/marc_index_ingester.rake
- Disable caching the advanced search page
- Override `app/helpers/blacklight_advanced_search/advanced_helper_behavior.rb` to initialize and use one query parser to check if a facet value is checked,  refer to method `def facet_value_checked?`
- Change advanced search facet views to use facet label directly instead of using `#facet_display_value`. The use of `facet_display_value` leads to a massive number of allocations when the field rendered has a lot of values.
- Remove advanced search page caching related logic from indexing
=> Disable advanced search caching and improve view rendering performance

app/assets/stylesheets/blacklight_catalog/_search_form.scss
=> Fixes the font size of the front page tagline.

lib/traject/extract_publication_date.rb, spec/models/marc_indexing_spec.rb
Rather than using 9999 as the ultimate far future end date that we truncate to this year, narrow that scope down so that any end year more than 100 years in the future is reduced to this year.
=> Limit end dates

Capfile, Gemfile, Gemfile.lock, README.md, config/deploy.rb, config/deploy/arch.rb, config/deploy/prod.rb, config/deploy/test.rb, dotenv.sample
- Capfile: removes deprecated gem from operation.
- Gemfile*: installs new gem that handles ip lookup.
- README.md: details the new instructions for deployment.
- config/deploy.rb: adds ENV loading for the IPs, extracts the ec2 gem variables, and locks config to new version.
- config/deploy/arch.rb, config/deploy/test.rb, and config/deploy/production.rb: swaps out server identifiers to the new gem process, with a default to variables.
- dotenv.sample: announces the necessary variables that should be set in the developer's `.env.development` file.
=> Uses new EC2 lookup gem for automated IP pulling.
